import csv
from pathlib import Path

OUT = Path(__file__).resolve().parent / "shard-0201-0300.csv"

HEADER = ["source_position", "item_code", "uom", "official_product_page",
          "official_image_url", "researcher_decision", "match_confidence",
          "finish_exact", "model_exact", "uom_assessment", "rights_status",
          "reason", "human_action"]

ROWS = [
    # ---------------- WAVE 1 ----------------
    dict(source_position="2856", item_code="CLI-HOS-13-23", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="PVC Wing Hose Clip 13-23, detected_model WH300. q:\"WH300\" hose clip PVC wing -> only generic hose clip results (McMaster, Jubilee-style wing clips, Alibaba); no brand carrying WH300. q:stainless steel hose clip 13-19mm GP Malaysia -> generic MY dealer listings only. WH300 appears to be a supplier internal code; no official product page exists anywhere (brand unknown). generic_unbranded + model_untraceable -> reject.",
         human_action=""),
    dict(source_position="2629", item_code="ELE-CAB-PVC-4.00MM-BLK-MTR", uom="MTR",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         uom_assessment="catalogue MTR matches cable sold per metre/100M coil",
         rights_status="no_asset",
         reason="KTK PVC Cable Black 100M, 4.0MM2. q:Ktk PVC insulated cable black 100M 4.0mm Malaysia -> no KTK OEM site; q:\"Ktk\" cable brand Malaysia PVC insulated wire -> KTK is an importer brand sold via MY distributors: p:samajaya.com.my/showproducts/productid/6421203 'KTK 2.5mm PVC Cable (Black)' and smjelectrical.com.my same family but ONLY 2.5mm variant listed; Lazada/Shopee 'MILLION KTK' marketplace-only. No official KTK manufacturer site exists and no 4.0MM2 black listing on any non-marketplace page. wrong-size family only -> reject.",
         human_action=""),
    dict(source_position="3534", item_code="ELE-PVC-CAS-1\"", uom="LGTH",
         official_product_page="https://chenta.com.my/portfolio/upvc-casing/",
         official_image_url="https://chenta.com.my/wp-content/uploads/2020/12/IMG_2334-1.jpg",
         researcher_decision="pending", match_confidence="B", finish_exact="yes", model_exact="yes",
         uom_assessment="LGTH ok - casing sold per length, mfr packs 1.83M lengths",
         rights_status="needs_permission",
         reason="Kancil 1 x 6FT PVC Casing. q:\"Kancil\" PVC casing 6FT electrical Malaysia -> chenta.com.my portfolio pages; Chenta Electrical Pipe Industries Sdn Bhd is the Malaysian manufacturer whose conduit brands include KANCIL (p:chenta.com.my/portfolio/pvc-conduit-kancil/ title 'PVC Conduit Kancil'). p:https://chenta.com.my/portfolio/upvc-casing/ says 'Size (inch) ... 1 ... Length 1.83M & UPON REQUEST, Color WHITE' -> size 1in x 1.83M(=6FT) white literally matches catalogue. og:image IMG_2334-1.jpg (800x533) is mfr product shot of uPVC casing. Caveat: string 'KANCIL' not printed on the casing page itself (only on their conduit pages); casing could be house-brand-neutral -> pending, brand_string_not_on_page.",
         human_action=""),
    dict(source_position="6012", item_code="BNW-WAS-1/4\"", uom="PKT",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="1/4 Iron Washer 20PCS/PCK. q:\"SW-260\"-style brand hunt n/a; q:1/4 iron washer pack Malaysia; q:BSW flat washer 1/4 Malaysia; q:iron washer DIN125 1/4 inch supplier; q:washer fastener Malaysia hardware; q:\"1/4\" washer mild steel pack -> all hits are generic unbranded fastener dealers (unicircle, standardbolts, flybear). No brand/OEM page exists for commodity washers. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="4856", item_code="BNW-NUT-SS304-M12", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         uom_assessment="PCS correct for individual nut",
         rights_status="no_asset",
         reason="SS 304 Nut M12. q:SS304 hex nut M12 DIN934 Malaysia supplier stainless -> p:standardbolts.net/product/hexagon-nut-din934/ (generic mfr/dealer, no SKU-level photo), p:unicircle.com.my/product/hex-nut-din-934/ (distributor page, generic), Shopee/Lazada marketplace listings. Commodity nut, no brand/OEM page anywhere. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="5197", item_code="FAS-PLU-PVC-GREY-SW260", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Grey PVC Wall Plug SW-260. q:\"SW-260\" PVC wall plug grey Malaysia -> zero SW-260 code hits; q:PVC wall plug grey Malaysia -> culmi.com.my 'PVC WALL PLUG (50 PCS/SHEET) GREY', geolaser, unicircle etc all generic unbranded sheets/packs. SW-260 is a supplier size-code, untraceable. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3311", item_code="CLI-HOS-GP-3/4\"", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="GP S/steel Hose Clip 3/4in (13-19MM). q:stainless steel hose clip \"13-19mm\" GP Malaysia -> p:kowhock.com.my B.I.Care K2514 (different brand, w/handle), velocitydiy generic 2pcs, ProHome88 Lazada, temotuf eezee - all other brands/generic. 'GP' here reads as general-purpose, not a brand. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3278", item_code="ABR-PAP-621-539", uom="SHT",
         researcher_decision="pending", match_confidence="C", finish_exact="no", model_exact="no",
         rights_status="unknown",
         reason="G800 EWD Hand Sanding Sheet. q:\"EWD\" hand sanding sheet G800 abrasive -> no EWD brand results (Burns/Axminster/3M only); q:\"EWD\" wet dry sandpaper sheet Malaysia -> 3M.com.my wetordry category, citraoasis sandpaper sheets P60-P2000, toptoa.my TOA/Nitto sandpapers - none branded EWD. EWD likely local importer initials; G800 grit spec matches commodity wet/dry 230x280mm sheets sold by MY abrasive suppliers but no EWD-branded official page found. generic_unbranded/untraceable_brand -> pending (grit+type plausible at citraoasis/toptoa but source would be non-authorised random dealer).",
         human_action=""),
    dict(source_position="6319", item_code="X-SWI-LWD-1WAY-2GANG", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Niko S - 1G1W Switch White. q:\"Niko\" 1G1W switch white Malaysia electrical -> p:niko.eu Belgian switch maker (Niko Original/Hydro ranges, EU naming, no '1G1W' SKU naming, no MY distribution shown); Shopee 'NIKO 13A SWITCH SOCKET authorized distributor' is marketplace-only and does not show this SKU; schneider vivace 1g1w hits are different brand. Malaysian 'Niko S' switch has no official product page anywhere. no_official_page -> reject.",
         human_action=""),
    dict(source_position="2627", item_code="ACE-HAM-ANC-1/4X2", uom="PCK",
         official_product_page="https://m.djhardware.com.my/index.php?ws=showproducts&products_id=3314613",
         official_image_url="https://cdn1.npcdn.net/images/1614411298ca817f9fc334e95d1b85c0319cb97c4e.png?md5id=37e83c96bcea8158cced5add35c02417&new_width=1000&new_height=1000&w=1587970780",
         researcher_decision="pending", match_confidence="C", finish_exact="no", model_exact="no",
         uom_assessment="PCK 10PCS/PCK plausible vs DJ Hardware box listings (Shopee shows pkt sizes)",
         rights_status="needs_permission",
         reason="Ace Hammer Drive Anchor 650 1/4x2 (=6x50mm=HDA650). q:\"Ace\" \"hammer drive anchor\" 650 Malaysia -> p:litaventure.com.my ACE BRAND HDA HDA630-HDA675 CA638 (JS-blocked stub, no image retrievable), soongwung.com/product/hammer-drive-anchor-ace/ sizes incl 1/4x2, chenhuphardware HDA-ZINC 'Authorized Distributor' page. q:\"ACE BRAND\" fasteners Malaysia hammer drive anchor HDA650 official -> no OEM site for Malaysian 'ACE BRAND'; acefastener.com is unrelated US dealer. Opened p:m.djhardware.com.my products_id=3314613 'ACE HDA ZINC ALLOY HAMMER DRIVE ANCHOR (WS)' og:image npcdn png 1000x1000 - family photo covering HDA630-675 range, size 650 not isolated in image/title. Distributor-not-proven-authorised + family_shot + size_unproven -> pending.",
         human_action=""),
    # ---------------- WAVE 2 ----------------
    dict(source_position="4864", item_code="FIT-PVC-TEE-20MMX15MM", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="PVC Fitting Tee Reducing 3/4 x 1/2. q:PVC tee reducing 20mm x 15mm Malaysia plumbing; q:\"PVC fitting\" tee reducing Malaysia supplier -> only generic plumbing dealers/marketplaces selling unbranded PVC fittings (same families as PVC-LINK etc). Commodity fitting, no OEM page exists. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="2962", item_code="CLI-HOS-13-19", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="PVC Wing Hose Clip 13-19, detected_model WH300 (same WH300 family as pos 2856). q:\"WH300\" hose clip PVC wing -> nothing; wing-type hose clips online are Jubilee/TIMco/Boltza (UK) or generic MY dealers. No WH300-branded page anywhere. generic_unbranded + model_untraceable -> reject.",
         human_action=""),
    dict(source_position="3043", item_code="X-ADH-TAP-MWP037A", uom="PCS",
         official_product_page="https://www.lazada.com.my/products/vago-ptfe-plumbing-thread-seal-tape-white-tape-thread-seal-tape-ptfe-plumbing-plumber-pipe-12mm-x-0075mm-i2755800250.html",
         official_image_url="https://img.lazcdn.com/g/p/729b11bbdfb7f63ba9debaa3551ee35d.jpg",
         researcher_decision="pending", match_confidence="B", finish_exact="yes", model_exact="yes",
         rights_status="needs_permission",
         reason="Vago Seal Tape 12MMX0.075MMX15M. q:\"Vago\" seal tape thread seal Malaysia -> p:lazada listing 'VAGO PTFE Plumbing Thread Seal Tape / White Tape ... 12mm x 0.075mm' spec matches catalogue exactly incl white; og:image fetched 720px. Also chenghuat.com.my 'VAGO HEAVY DUTY PTPE TAPE 19MM X 0.1MM X 15M' (different size) and engtex/engsenghan 'Wago Brand' PTFE (different brand WAGO). NO Vago OEM/official site exists anywhere -> per protocol marketplace allowed when no OEM page exists. Downgraded from candidate to pending because roll length 15M not visible in fetched title/excerpt (only 12x0.075 proven) and marketplace authenticity unverifiable.",
         human_action=""),
    dict(source_position="4668", item_code="SOC-PVC-BOX-6MM", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="PVC 2WAY Box 3/4. q:\"PVC 2 way box\" 3/4 conduit junction Malaysia -> p:kvc.com.my 'PVC BOX 2 WAY 20MM (3/4'') WHITE' MPN IWCB 20-2W (importer part, KVC industrial distributor), Lazada/Shopee generic conduit boxes. Item code says 6MM vs display 3/4(=20MM) internally inconsistent; commodity unbranded box, no OEM page. generic_unbranded + size_conflict_in_catalogue_row -> reject.",
         human_action=""),
    dict(source_position="3398", item_code="CLI-HOS-GP-7/8\"", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="GP S/steel Hose Clip 7/8in (13-23MM). Same generic family as pos 3311: q:stainless hose clip 13-23mm Malaysia -> B.I.Care/KOW HOCK (other brand), velocitydiy, ProHome88 marketplace, wthose supplier pages. 'GP'=general purpose, no brand. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3061", item_code="SWI-S/SKT-LWD-4013-13A", uom="PCS",
         official_product_page="https://www.homepro.com.my/p/1007443",
         official_image_url="https://statice.homepro.co.th/homepromy/ART_IMAGE/10/074/1007443/1000x1000/09052025_1007443$Imagec1.jpg",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="PCS correct for one socket outlet",
         rights_status="needs_permission",
         reason="NNE 13A S/skt model 813/S. q:\"NNE\" 13A switch socket outlet 813 Malaysia -> p:homepro.com.my/p/1007443 titled '13A 1G FLUSH SWITCH SOCKET OUTLET 813/S NNE', SKU 1007443, page text: 'SIRIM Approved / High Impact Polycarbonate / FIRE RESISTANCE BODY'; model string '813/S NNE' seen literally in title. HomePro MY is a major electrical retail chain (og:image 1000x1000 product photo). NNE brand has no accessible OEM site (nne.com is unrelated pharma engineering) -> retailer page acceptable under no-OEM rule. Colour not stated on page -> finish unproven, confidence B.",
         human_action=""),
    dict(source_position="3069", item_code="CLI-HOS-GP-1.1/2\"", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="GP S/steel Hose Clip 1.1/2in (21-38MM). Same generic family as 3311/3398; q:hose clip 21-38mm stainless Malaysia -> generic dealers only (wthose.com.my hose clip supplier since 1996, no brand SKU pages). No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3221", item_code="DOR-STO-25X25MM", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Red Rubber Door Stopper 25X25MM. q:red rubber door stopper 25mm Malaysia; q:rubber door stop hardware Malaysia -> generic hardware dealers/marketplace only, unbranded commodity. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3252", item_code="SWI-PLU-MK-654-13A", uom="PCS",
         official_product_page="https://www.sierraplus.com.my/mk-654-13amp-plug-top-sirim-white",
         official_image_url="https://www.sierraplus.com.my/image/sponline/image/cache/data/all_product_images/product-806/mk-654-13amp-plug-top-sirim-white-1200x1200.jpg",
         researcher_decision="candidate", match_confidence="A", finish_exact="yes", model_exact="yes",
         uom_assessment="PCS correct for single plug top",
         rights_status="needs_permission",
         reason="Mk 654 Whi 13A Plug Top 3PIN. q:MK 654 WHI 13A plug top white Malaysia -> p:sierraplus.com.my/mk-654-13amp-plug-top-sirim-white opened: spec table 'MK/PT13A654 | 13Amp Plug Top | Sirim Yes | Casing Colour White', images 1200x1200 white plug top; p:hslelectrical.com.my/mk-654whi-13a-plug-top says 'MK 654WHI 13A PLUG TOP - SIRIM APPROVED *Made in MALAYSIA* Model : 654'; p:yhelectrical.com 'Brand：MK Model : 654 13Amp 250V Fused Plug'. OEM check: mkelectric.com (Honeywell UK) carries only UK range (646/647), Malaysian SIRIM 654 made by MK Electric (M) Sdn Bhd has NO online OEM product page anywhere -> dealer page acceptable under no-OEM rule. Model 654 + white + 13A + 3PIN all proven by page text and image -> A.",
         human_action=""),
    dict(source_position="2773", item_code="CUT-BLA-ECL-1218T", uom="PCS",
         official_product_page="https://camdentools.com/en-US/product/eclipse-aa45e-pred-pb-bimetal-hss-hacksaw-blades-18tpi-pack-of-100-TLS-ECL-AA45E-PRED-PB-EN_US",
         official_image_url="https://assets.r2.camdentools.com/media/58e4bcfa-8c48-4a99-9bd2-5e265dbe2d65-large.webp",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="catalogue PCS = single blade; sources sell packs of 10/100 - pack-vs-piece trap noted, image shows blades not packaging count claim",
         rights_status="needs_permission",
         reason="Eclipse Hacksaw Blade 12MM X 18T Predator (=12.5mm wide, 300mm long, 18TPI per mfr spec; item_code 1218T=12in/18T consistent). q:\"Eclipse\" hacksaw blade 12mm 18T predator; q:Eclipse Predator EC-AA45EPRED; q:eclipsetools.com predator 18tpi -> model identified as ECL-AA45E-PRED-PB (aka EC-AA45EPRED Blackwoods Mfr#). p:camdentools.com product page opened: 'Eclipse AA45E-PRED-PB Predator Bimetal HSS Hacksaw Blades 18TPI... Blade Size: 300mm x 12.5mm x 0.63mm TPI 18', large webp asset. Official eclipsetools.com search returned no crawlable product URLs -> dealer page used under no-OEM-page-found rationale. Model+size proven; blade finish n/a -> B.",
         human_action=""),
    # ---------------- WAVE 3 ----------------
    dict(source_position="3465", item_code="ABR-PAP-621-529", uom="SHT",
         researcher_decision="pending", match_confidence="C", finish_exact="no", model_exact="no",
         rights_status="unknown",
         reason="G100 EWD Hand Sanding Sheet - sibling of pos 3278 (G800). q:\"EWD\" wet dry sandpaper sheet Malaysia; q:\"EWD\" hand sanding sheet abrasive -> no EWD-branded page anywhere; MY commodity suppliers citraoasis.com.my (230x280 P60-P2000) and toptoa.my sell identical spec sheets under TOA/Nitto/generic brands. EWD = untraceable local importer initials -> pending generic_unbranded.",
         human_action=""),
    dict(source_position="3171", item_code="SHH-SINKER-NO.1", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Single Head Sinker No.1 (2PCS/PCK) fishing lead weight. q:fishing sinker single head lead Malaysia tackle -> Shopee/Lazada marketplace generic lead sinkers only; 'No.1' is a local size designation used by Malaysian tackle shops; no brand/OEM page exists. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="5387", item_code="ACE-NUTS-5/16\"X38MM", uom="PCS",
         official_product_page="https://m.chentat.com/index.php?ws=showproducts&products_id=4254590&cat=ACE-Brand",
         official_image_url="https://cdn1.npcdn.net/images/16695654923c20cade2dab2d08a0e473c455383710.jpg?md5id=b4c148b36ad0c21e46d1fc1f51d51585&new_width=1000&new_height=1000&w=1690123166",
         researcher_decision="pending", match_confidence="C", finish_exact="no", model_exact="no",
         rights_status="needs_permission",
         reason="Ace Brand BSW Hexagon Long Nut LN-5/16x38MM. q:\"ACE\" brand BSW hexagon long nut Malaysia fastener -> p:m.chentat.com ACE Brand category lists 'Hexagon Long Nut' (og:image fetched); p:chenhuphardware 'Hexagon Long Nut ACE BRAND Authorized Distributor'; p:chenghuatgroup.com.my shows exact-title 'HEXAGON LONG NUT [LN-3/8''] Brand: ACE BRAND' proving the LN-naming scheme but only the 3/8 variant page located; litaventure JS-blocked. No OEM site exists for Malaysian ACE BRAND fasteners. Size LN-5/16 not isolated on any opened page (family photo); source image maxes at 456x456 (CDN original, below 500px bar) -> pending C + low_res.",
         human_action=""),
    dict(source_position="2884", item_code="ELE-T5-4FT-CIELO-D/L", uom="PCS",
         official_product_page="https://cimalighting.com.my/product/cielo-gen2-t5-led-batten-2ft-3ft-4ft-10w-14w-18w-sirim-cetificated",
         official_image_url="https://cdn1.sgliteasset.com/eluxelig/images/product/product-5938586/klRotFIO6772683db025f_1735551038.jpg",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="PCS correct per fitting; sold as complete batten",
         rights_status="needs_permission",
         reason="Cielo T5 LED Fitting 4FT 18W DL(=daylight 6500K, internal code DL-860). q:Cielo T5 LED fitting 4FT 18W Malaysia -> CIELO GEN2 T5 LED BATTEN [2FT/3FT/4FT][10W/14W/18W] SIRIM certified sold on cimalighting.com.my webstore ('Brand: Cielo', CIMA Lighting) - brand-owner store; also Lazada/Shopee same GEN2 family. Opened product page; full-size gallery asset saved. Page proves Cielo GEN2 T5 4FT 18W family; daylight/warmwhite are selectable options so DL-vs-WW not pinned in static text/image -> B (sibling row 3223 is the WW variant).",
         human_action=""),
    dict(source_position="2770", item_code="PLUG-TOP-UMS-13A", uom="PCS",
         official_product_page="https://www.samajaya.com.my/showproducts/productid/5325840/ums-pt130rs-pt130r-s-pt130rs-13a-3-pin-plug-top-13a-plug-top/",
         official_image_url="https://cdn1.npcdn.net/images/ac4f39978df41cafce9a9ff89e840dde_1732086813.jpeg",
         researcher_decision="candidate", match_confidence="A", finish_exact="yes", model_exact="yes",
         uom_assessment="PCS correct for one plug top",
         rights_status="needs_permission",
         reason="Ums 13A Plugtop PT130R-S. q:UMS PT130R-S 13A plug top Malaysia -> p:samajaya.com.my productid 5325840 opened: 'Model : PT130R-S/ PT130R S/ PT130RS 13A 3 Pin Plug Top. Brand : UMS. Made in Malaysia.' og:image npcdn product photo; p:brilliantelectrical.com.my productid 5889440 says 'UMS 13A PLUG TOP PT 130R-S *Model : PT130R-S *Colour : White *SIRIM APPROVED *MADE IN MALAYSIA'; p:ne2u.com.my 'UMS PT130R-S 13A Resilient (PC) Plug Top'. UMS manufacturer (United MS Electrical Mfg (M) Sdn Bhd) has ums-neiken.com but no crawlable individual SKU page found for PT130R-S -> dealer pages acceptable. Model+white+13A proven by page text and image -> A.",
         human_action=""),
    dict(source_position="4816", item_code="ACE-NUTS-3/8\"X38MM", uom="PCS",
         official_product_page="https://www.chenghuatgroup.com.my/showproducts/productid/4107983/cid/428833/hexagon-long-nut-ln38039039/",
         official_image_url="https://cdn1.npcdn.net/images/1660989793e027aab155c75045ba6ee50110f57dff.png",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         rights_status="needs_permission",
         reason="Ace Brand Bsw Hexagon Long Nut LN-3/8x38MM. Same search set as pos 5387. p:chenghuatgroup.com.my showproducts 4107983 opened: title/og:alt literally 'HEXAGON LONG NUT [LN-3/8'']', 'RM1.10 Brand: ACE BRAND Category: HEXAGON LONG NUT'; og:image product photo saved. No OEM site for Malaysian ACE BRAND fasteners (importer brand) -> dealer page acceptable. Model proven; plating/finish (zinc per Shopee listing) not stated on dealer page -> B.",
         human_action=""),
    dict(source_position="3396", item_code="CHA-PVC-BEL-G6MM", uom="MTR",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="PVC coated chain green 6MM, detected brands 'Cn/kh'. q:PVC coated chain green 6mm Malaysia; q:green vinyl coated chain 6mm supplier -> generic import chains at MY dealers/marketplace; 'CN/KH' reads as China/Kampung-style sourcing abbreviations not traceable brands. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="2970", item_code="IND-FIL-100MM", uom="ROLL",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Stretch Film 4IN x 230GM roll. q:stretch film 4 inch 230g Malaysia; q:hand stretch wrap 100mm Malaysia supplier -> packaging commodity at MY dealers/marketplaces, unbranded or house brands. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="2931", item_code="FAS-SCR-CSK-1 1/4\" X 8G", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Sr Csk Tapping Screw 1 1/4 x 8G (20PCS/PCK). q:countersunk self tapping screw 8G x 1-1/4 Malaysia pack; q:\"SR\" screw brand Malaysia -> 'Sr' is the shop's internal abbreviation (appears across many SKUs of this catalogue), commodity screws sold loose/packed by all MY hardware dealers. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3733", item_code="FAS-SCR-TAP-CSK-8#1\"-PCK", uom="PACK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="8 x 1in CSK Self Tapping Screw flat head (10PCS/PCK). Same query set as pos 2931: commodity countersunk self-tappers, every MY hardware dealer carries unbranded packs; no OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    # ---------------- WAVE 4 ----------------
    dict(source_position="5963", item_code="ELE-PVC-TEE-3W", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="19MM Tee Box (3WAY Box). Same commodity family as pos 4668: q:\"PVC 3 way box\" conduit 19mm Malaysia -> generic conduit boxes at MY dealers/marketplaces, unbranded. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="4205", item_code="PIC-HAN-GOL-1-1/2\"", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Golden Picture Hanger-m'sia 1-1/2 (2PAIR/PCK). q:\"Golden\" picture hanger Malaysia hardware brand -> no Malaysian 'GOLDEN' brand hanger page exists (hits are GoldenEar speakers on Lazada, generic golden-colour hook kits on Amazon/Lazada marketplaces). 'GOL'=golden colour, m'sia=local pack. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="4113", item_code="HOS-CON-13-16MM", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Power Hose Joint 13-16MM. q:hose joint/mender connector 13-16mm Malaysia -> generic hose menders at MY dealers/marketplaces, unbranded. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3872", item_code="PIP-UPVC-5255-1.1/2\"", uom="MTR",
         official_product_page="https://unimechengineering.com.my/product/upvc-pipe-2/",
         official_image_url="https://unimechengineering.com.my/wp-content/uploads/2022/03/UPCV-Pipe-BS4255-1.jpg",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="MTR correct; pipe supplied in 6M lengths per page",
         rights_status="needs_permission",
         reason="1 1/2(40MM) x 6M UPVC Pipe BS5255. q:uPVC pipe BS5255 40mm x 6M Malaysia -> p:unimechengineering.com.my/product/upvc-pipe-2/ opened: 'Material: UPVC, Spec: BS5255, Length: 6 meter, Size: 32 - 50mm' with product photo; p:sanifixhardware.com BINA PLASTIC SWV pipes comply MS1063 equivalent BS5255 size 43MM(1-1/2)x5.8M (mfr catalogue PDF exists but not SKU-cropped); p:spind.com.my same standard family. Catalogue brand blank (commodity spec item); BS5255+6M+size range proven by page text and image shows white SWV pipe. Unimech = MY industrial supplier; no single-OEM page for this commodity spec -> candidate B.",
         human_action=""),
    dict(source_position="3308", item_code="BNW-BOL-SS304-M10-30MM", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="SS 304 Bolt M10x30MM. Same commodity query set as pos 4856 (DIN931/933 SS304 bolts sold unbranded by unicircle/standardbolts/flybear + marketplaces). No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3188", item_code="SHH-SINKER-NO.2", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Single Head Sinker No.2 (2PCS/PCK) - sibling of pos 3171. Same search set: marketplace-only generic lead sinkers, local No.x sizing, no brand/OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="2986", item_code="CUT-DIS-HIT-GRI-4X6MM", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Grinding Wheel 4x6MM (100X6X16MM) grey. q:grinding wheel 100x6x16 grey Malaysia; q:'HIT' grinding disc brand -> 'HIT GRI' reads as hitachi-grey/generic descriptors; commodity depressed-center wheels sold unbranded everywhere. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3391", item_code="ANT-KILL-BAIT", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Ant Killing Bait 35GM. q:ant bait 35g Malaysia; q:ant killer bait station Malaysia -> consumer insecticide brands (Baygon/Fendona etc.) but none matching a 35GM loose pack under this house-code name; likely repacked local goods. No OEM page identifiable. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="4732", item_code="WAL-PLU-S/S-CC226-M8X70MM", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="S/steel Wall Plug K103-304 M8X70MM CC226. q:\"K103-304\" OR \"CC226\" stainless steel wall plug M8 Malaysia -> zero hits for either code anywhere; nearest products are generic SUS304 sleeve anchors at lianhoaircond/sklhardware/aurous without these codes. CC226/K103-304 are supplier internal codes, untraceable. generic_unbranded + code_untraceable -> reject.",
         human_action=""),
    dict(source_position="4313", item_code="FAS-SCR-DRY-WHI-6#1.1/4\"", uom="PCK",
         researcher_decision="pending", match_confidence="C", finish_exact="no", model_exact="no",
         rights_status="needs_permission",
         reason="Hunter/wh Drywall Screw 6# x 1-1/4 (20PCS/PCK). q:\"Hunter\" drywall screw gypsum Malaysia brand whit black -> HUNTER is an established drywall-screw brand distributed regionally: p:viborgtrading.com/product-page/hunter-drywall-screw 'Available in two colours: BLACK, WHITE, available in different sizes'; p:singbrothers.com.sg HUNTER WHITE DRYWALL SCREW (bugle phillips fine thread C1022); p:sionghua.com.sg BLACK sizes incl 6x1-1/4. No Hunter OEM site exists; MY dealer pages for the exact white 6x1-1/4 variant not found (SG dealers only) -> pending C.",
         human_action=""),
    # ---------------- WAVE 5 ----------------
    dict(source_position="6072", item_code="ELE-PVC-CRO-4W", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="19MM Cross Box 4WAY - same commodity conduit-box family as pos 4668/5963: unbranded PVC junction boxes at MY dealers/marketplaces only. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="4349", item_code="SWI-LAM-HOL-SE220E-E27", uom="PCS",
         official_product_page="https://www.sierraplus.com.my/se-220-e27-batten-lamp-holder-socket-light-bulb-holder-c-w-base-white",
         official_image_url="https://www.sierraplus.com.my/image/sponline/image/cache/data/all_product_images/product-1110/se-220-e27-batten-lamp-holder-socket-light-bulb-holder-c-w-base-white-a-900x900.jpg",
         researcher_decision="candidate", match_confidence="A", finish_exact="yes", model_exact="yes",
         uom_assessment="PCS correct for one batten holder",
         rights_status="needs_permission",
         reason="E27 Batten Holder White model SE220E. q:\"SE220E\" E27 batten holder lamp holder -> p:sierraplus.com.my opened: title 'SE-220 E27 Batten Lamp Holder / Socket Light Bulb Holder c/w Base (White)', spec table 'HD220E27-WH | E27 Batten Holder | Colour White | Plastic | 250V 4amp', 900x900 product photos; p:samajaya.com.my productid 5326291 'SE-220/ SE220/ SE 220 E27 Batten Holder'; marketplace SE220 listings match same spec. Commodity item with no brand (Sierra Plus Brand: N/A), no OEM site exists anywhere -> dealer page acceptable under no-OEM rule. Model SE-220 + white proven by title/spec text and image -> A.",
         human_action=""),
    dict(source_position="5548", item_code="FAS-SCR-TAP-CSK-8#1 1/2\"", uom="PACK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="8 x 1-1/2 CSK Self Tapping Screw flat head (10PCS/PCK) - sibling of pos 3733/2931 query set. Commodity countersunk self-tappers, unbranded at all MY dealers. No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="4303", item_code="CAP-01.5UF-415V-CBB61", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Capacitor CBB61 1.5uF square black. q:CBB61 capacitor 415V 1.5uF fan motor Malaysia -> CBB61 is a generic Chinese film-capacitor type code, not a brand; sold unbranded (hometech2u.com.my lists CBB61 1.5uF but 450VAC - voltage differs from catalogue 415V). No OEM brandable page. generic_unbranded + voltage_variant_mismatch -> reject.",
         human_action=""),
    dict(source_position="3181", item_code="FAS-SCR-TAP-CSK-8#2 1/2\"", uom="PACK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="8 x 2-1/2 CSK Self Tapping Screw flat head (10PCS/PCK) - sibling of pos 5548/3733. Commodity unbranded screws, no OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3338", item_code="SHH-SINKER-NO.5", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Single Head Sinker No.5 (1PCS/PCK) - sibling of pos 3171/3188. Same search set: local No.x lead sinkers sold loose/marketplace only, no brand/OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3449", item_code="FAS-SCR-P/H-3/4\" X 8#", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Sr P/h Self Drilling Screw 3/4 x 8 (20PCS/PCK). 'Sr'=shop internal prefix (see pos 2931); pan-head self-drillers are commodity items stocked unbranded by unicircle/standardbolts etc. No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3571", item_code="TAP-WIR-3MSCTBLUE", uom="PCS",
         official_product_page="https://www.3mindia.in/3M/en_IN/p/d/v101862014",
         official_image_url="https://multimedia.3m.com/mws/media/2585693J/3m-temflex-general-use-vinyl-electrical-tape-150-blue-jpg-file-in.jpg?width=1200",
         researcher_decision="pending", match_confidence="B", finish_exact="yes", model_exact="yes",
         uom_assessment="PCS = one roll",
         rights_status="needs_permission",
         reason="3M Blue Vinyl Elec Tape '150' = 3M(TM) Temflex(TM) General Use Vinyl Electrical Tape 150. q:\"Temflex 150\" vinyl electrical tape blue Malaysia -> OFFICIAL OEM page p:www.3mindia.in/3M/en_IN/p/d/v101862014 opened: '3M(TM) Temflex(TM) Vinyl Electrical Tape 150, Blue, 18 mm x 6 m', '3M Product Number 150', 'Product Colour Blue' with official multimedia.3m.com asset (1200px) saved. MY coverage: p:3m.com.my hosts the Temflex General Use family page; MY-market 5M roll seen on Lazada '(Ready Stock) 3M 150 Temflex... Size 18mm x 5m x 0.13mm' (blue/yellow/black); Alliance Supplies Sdn Bhd (alliancesuppliesonline.onesync.my productid 6132532) lists Temflex 150 but JS-blocked. Downgrade candidate->pending: catalogue size 18MMX5MM matches MY-market 5M roll which is only provable on marketplace; official OEM pages show 6M variant.",
         human_action=""),
    dict(source_position="3092", item_code="FAS-SCR-DRY-WHI-6#1\"BOX", uom="BOX",
         researcher_decision="pending", match_confidence="C", finish_exact="no", model_exact="no",
         rights_status="needs_permission",
         reason="Hunter/wh Drywall Screw 6# x 1 BOX - sibling of pos 4313. HUNTER drywall screw brand confirmed at viborgtrading.com (BLACK+WHITE, different sizes), singbrothers.com.sg HUNTER WHITE DRYWALL SCREW, sionghua.com.sg BLACK sizes incl 6x1. No Hunter OEM site anywhere; no MY non-marketplace page for the exact white 6x1 box -> pending C.",
         human_action=""),
    dict(source_position="4585", item_code="PIC-HAN-GOL-1\"", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Golden Picture Hanger-m'sia 1 (2PAIR/PCK) - sibling of pos 4205. Same query set: no Malaysian 'GOLDEN' hanger brand exists online; golden-colour hook kits on marketplaces only. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    # ---------------- WAVE 6 ----------------
    dict(source_position="3141", item_code="SHH-SINKER-NO.6", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Single Head Sinker No.6 (1PC/PCK) - sibling of pos 3171/3188/3338. Same search set: local No.x lead sinkers, marketplace-only, no brand/OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="2928", item_code="WIN-HOO-PIN-8406", uom="PCK",
         official_product_page="https://www.windowlife.my/product/8406-pin-hook/",
         official_image_url="https://www.windowlife.my/wp-content/uploads/2021/08/8406-Pin-Hook-scaled.jpg",
         researcher_decision="pending", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="catalogue 25PCS/PCK is a repack; source sells 500pcs/box bulk - pack_size_mismatch",
         rights_status="needs_permission",
         reason="Sr Pin Hook 8406 (25PCS/PCK). q:\"pin hook\" 8406 hardware Malaysia -> p:windowlife.my/product/8406-pin-hook/ opened: '8406 Pin Hook Side Pin Hook (500pcs/box) SKU: HOOK-8406 RM16.00' with 2048px product photo saved; marketplace 8406 curtain pin-hook listings corroborate the 8406 model code (32x16mm S-shaped pin-on hook). 'Sr'=shop prefix; no OEM exists - 8406 is a commodity model number across Asian curtain hardware -> dealer page acceptable under no-OEM rule. Model proven by page text+image; downgraded to pending only for pack-size mismatch (25-pc retail pack vs 500-box).",
         human_action=""),
    dict(source_position="3153", item_code="BNW-BOL-SS304-M10-50MM", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="SS 304 Bolt M10x50MM - sibling of pos 3308 query set (DIN931 SS304 unbranded commodity at unicircle/standardbolts/flybear + marketplaces). No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3361", item_code="SWI-ADA-MS3106N", uom="PCS",
         official_product_page="https://www.homepro.com.my/p/1075259",
         official_image_url="https://statice.homepro.co.th/homepromy/ART_IMAGE/10/752/1075259/1000x1000/09052025_1075259$Imagec1.jpg",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="PCS = one travel adaptor",
         rights_status="needs_permission",
         reason="Morries Uk Plug Travel Adaptor MS3106N. q:\"Morries\" MS3106N UK plug travel adaptor Malaysia -> p:homepro.com.my/p/1075259 opened: title 'MORRIES TRAVEL ADAPTOR WITH LED INDICATOR MS3106N WHITE', SKU 1075259, spec text 'Input 250V A/C ... Max Load 13A'; og:image 1000x1000 product photo saved; p:yuanming.com.my hosts official distributor PDF wp-content/uploads/2025/08/MORRIES-MS3106N-UK-PLUG-TRAVEL-ADAPTOR.pdf titled 'MORRIES MS3106N UK PLUG TRAVEL ADAPTOR' (model literal); SG retailers horme/hardwarecity corroborate MS3106N/-BK variants. Morries brand site not directly reachable -> retailer+distributor-PDF evidence acceptable. Model proven by page text; colour white vs catalogue-unspecified -> B.",
         human_action=""),
    dict(source_position="3533", item_code="ELE-D/L-HOME-2103-18W-6500K", uom="PCS",
         official_product_page="https://www.lazada.com.my/products/led-panel-light-downlight-18-watt-6inch-6500k-daylight-i1345104588.html",
         official_image_url="https://img.lazcdn.com/g/p/913f605ee2364fad2b7df5d308af70cf.jpg",
         researcher_decision="candidate", match_confidence="B", finish_exact="yes", model_exact="yes",
         uom_assessment="PCS = one downlight fitting",
         rights_status="needs_permission",
         reason="Hermanns Downlite round 6500K daylight 18W. q:\"Hermanns\" OR \"Hermann\" downlight Malaysia 18W 6500K -> p:lazada.com.my i1345104588 opened: 'HERMANNS Daylight Plastic ... MODEL: HRM-1060R-18W, POWER: 18WATT ... 18 WATT 6INCH 6500K DAYLIGHT', og:image fetched. HERMANNS is a Malaysian lighting brand but NO official Hermanns product page exists anywhere online -> per protocol marketplace allowed when no OEM page exists (recorded here). Model string HRM-1060R-18W + 6500K daylight proven in listing text/image; source-tier caveat marketplace_only_no_oem_exists -> candidate B.",
         human_action=""),
    dict(source_position="3999", item_code="FAS-RIV-PAT-1/8\"X1/2\"-PCK", uom="PCK",
         official_product_page="https://soongwung.com/product/jaguar-blind-rivet/",
         official_image_url="https://soongwung.com/wp-content/uploads/2024/02/C72.png",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="catalogue PCK 20PCS retail pack; source lists per-size boxes - packing granularity differs, same item",
         rights_status="needs_permission",
         reason="Blind Rivet Jaguar 1/8 x 1/2 (20PCS/PCK). q:\"Jaguar\" blind rivet Malaysia fastener brand -> p:hardwarehouse.com.my/product/264/Jaguar-Blind-Rivet/ 'Jaguar Blind Rivet ... Made in Malaysia' size list literally includes '1/8\" x 1/2\", 1/8\" x 1/4\", 1/8\" x 5/16\", 1/8\" x 3/4\"' matching all four catalogue rivet SKUs (pos 3999/4524/3863/4257) but its image CDN serves only SPA HTML (bytes not fetchable). p:soongwung.com/product/jaguar-blind-rivet/ opened instead: 'JAGUAR - Blind Rivet ... Diameter Available 1/8\" (3.2MM) 5/32\" (4.0MM) 3/16\" (4.8MM)' with product photos C72/C73/C74 saved (C72=1/8in). No Jaguar rivets OEM site exists (MY-made import brand sold via dealers) -> dealer page acceptable under no-OEM rule. Size 1/8 proven via page text+image; aluminium finish unproven -> B.",
         human_action=""),
    dict(source_position="6743", item_code="FAS-SCR-DRY-WHI-6#3/4\"", uom="PCK",
         researcher_decision="pending", match_confidence="C", finish_exact="no", model_exact="no",
         rights_status="needs_permission",
         reason="Hunter/wh Drywall Screw 6# x 3/4 (20PCS/PCK) - sibling of pos 4313/3092. HUNTER brand confirmed at viborgtrading/singbrothers/sionghua (SG dealers); sionghua BLACK page enumerates sizes incl 6 x 3/4 but WHITE 3/4 MY non-marketplace page not found; no Hunter OEM anywhere -> pending C.",
         human_action=""),
    dict(source_position="3658", item_code="DOR-ROL-CAT-RDL304", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="S/s Double Roller Catch (4PCS/PCK) RDL304. q:double roller catch stainless RDL304; q:roller catch cabinet stainless Malaysia -> generic cabinet catches at MY dealers/marketplaces, none carrying RDL304 code; code appears supplier-internal. No OEM page. generic_unbranded + code_untraceable -> reject.",
         human_action=""),
    dict(source_position="3039", item_code="SWI-SOC-ELE-E0813B", uom="PCS",
         official_product_page="https://www.retouch.my/showproducts/productid/5703834/cid/577199/sockets/",
         official_image_url="https://cdn1.npcdn.net/images/cbebcb1cca445d2e69e75cb4adf46888_1739431054.png",
         researcher_decision="pending", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="PCS = one switched socket",
         rights_status="needs_permission",
         reason="Elegance 13A Flat Pin Double Pole Switched Socket black E0813B. q:\"Elegance\" switch socket E0813B 13A black Malaysia -> OFFICIAL brand site p:retouch.my (Broadlink Marketing Sdn Bhd, reTOUCH) Elegance Sense's Black sockets category opened with npcdn series image; model code proven by listings: Shopee reTouch variant table '13A 1 Gang Socket Big Rocker (E0813B)', thelivingdepot 'RETOUCH ELEGANCE 13A FLAT PIN DOUBLE POLE SWITCH SOCKET W/O NEON BLACK - E0813B RM14.00'. Downgraded from candidate because official retouch.my page found is category-level (E0813B SKU page not crawlable this session), so image cannot be pinned to exact SKU/colour -> pending B.",
         human_action=""),
    dict(source_position="3283", item_code="FAS-SCR-F/H-1 1/4\" X 8#", uom="PKT",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Sr F/h Self Drilling Screw 1 1/4 x 8 (20PCS/PCK) - sibling of pos 3449. Commodity flat-head self-drillers, unbranded at MY dealers. No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    # ---------------- WAVE 7 ----------------
    dict(source_position="3881", item_code="ABR-PAP-621-531", uom="SHT",
         researcher_decision="pending", match_confidence="C", finish_exact="no", model_exact="no",
         rights_status="unknown",
         reason="G150 EWD Hand Sanding Sheet - sibling of pos 3278/3465. Same query set: no EWD-branded page exists anywhere; MY abrasive suppliers (citraoasis, toptoa) carry identical-spec unbranded/TOA sheets. EWD = untraceable local importer initials -> pending C generic_unbranded.",
         human_action=""),
    dict(source_position="6739", item_code="BNW-WAS-M5", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="M5 Washer (20PCS/PCK). Commodity metric flat washer - same query set as pos 6012/4856: unbranded at unicircle/standardbolts/flybear + marketplaces. No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="2644", item_code="BRO-PLA-SB200", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Plastic Broom 260G SB200. q:\"SB200\" plastic broom Malaysia -> zero SB200 hits; MY broom manufacturers rayaco.com.my/broomstar.com.my/xintrading carry their own model codes, none matching SB200. Supplier internal code untraceable. No OEM page. generic_unbranded + code_untraceable -> reject.",
         human_action=""),
    dict(source_position="2708", item_code="TOO-MAG-MC03A", uom="PCK",
         official_product_page="https://www.wzmvm.com/product/mc-03/",
         official_image_url="https://www.wzmvm.com/wp-content/uploads/2024/04/MC-03A.jpg",
         researcher_decision="pending", match_confidence="B", finish_exact="no", model_exact="yes",
         rights_status="needs_permission",
         reason="Magnetic Catch (4PCS/PCK) MC-03A. q:\"Magnetic catch\" \"MC03A\" OR \"MC-03A\" cabinet -> p:wzmvm.com/product/mc-03/ 'MC-03A' with og:image MC-03A.jpg 600x600 saved; Volza trade data shows 'HOMEAID MAGNETIC CATCH MC-03A (WHITE) - BRAND HOMEAID' identifying the OEM brand as HOMEAID, but NO HOMEAID official site or MY authorised-dealer page exists online (only marketplaces). Model proven by dealer title/image; source is a foreign hardware e-shop not an authorised MY distributor -> pending B.",
         human_action=""),
    dict(source_position="3623", item_code="CUT-DIS-MARK-12300-P024", uom="PCS",
         official_product_page="https://www.mrmarks.com/index.php?ws=showproducts&products_id=2160710",
         official_image_url="https://cdn1.npcdn.net/image/156084571199cb84b713796168898828c90a9038f9.jpg?md5id=40a115d736494ae0bf5b6b65c715868d&new_width=1000&new_height=1000&w=1534135529",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="PCS = one disc; mfr packs box of 25",
         rights_status="needs_permission",
         reason="Mr. Mark P24 Master Fibre Disc Blk (100x6x16 family). q:\"Mr. Mark\" P24 fibre disc Master Malaysia abrasive -> OFFICIAL brand site p:mrmarks.com (Mr.Mark Tools (M) Sdn Bhd, Ulu Tiram JB) product page products_id=2160710 opened: 'MK-WEL-12300 MASTER FIBRE DISC (100mm / 4\")' - 'abrasives Silicon Carbon coated on the vulcanized fibre backing... removing rust, old paint'; og:image npcdn 1000px disc photo saved; mdex.my corroborates 'P24 MASTER Fiber Disc (Silicon Carbon) (MK-W-12300-24)'. Catalogue code MARK-12300-P024 maps literally to MK-WEL-12300-P24 on the manufacturer's own site. Black SiC disc colour implied by image but 'black' not stated in text -> finish unproven, B.",
         human_action=""),
    dict(source_position="3343", item_code="CUT-ELE-EFM430", uom="PCS",
         official_product_page="https://m.djhardware.com.my/index.php?ws=showproducts&products_id=3308430",
         official_image_url="https://cdn1.npcdn.net/images/16139647540e968fbe3cbc80073cdae67763457cf4.png",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="PCS = one flexible grinding disc",
         rights_status="needs_permission",
         reason="Gold Elephant Flexible Grinding Disc EFM-430. q:\"Gold Elephant\" EFM-430 flexible grinding disc -> p:m.djhardware.com.my products_id=3308430 opened: 'GOLD ELEPHANT INDUSTRIAL LINE FLEXIBLE GRINDING DISC METAL EFM 430 (WS)' og:image npcdn 1000px saved; Lazada listing '[GOLD ELEPHANT] FLEXIBLE GRINDING DISC METAL EFM430 ... 102mmX3.0X16'; distributor subsite goldelephant.bunseng.com.my exists (Bun Seng) but its disc page is JS-thin. Gold Elephant = Zhuhai Elephant Abrasives brand (eleabrasives.com OEM domain exists but has no crawlable EFM430 SKU page) -> MY dealer page used as best available evidence. Model EFM 430 literal in title -> B.",
         human_action=""),
    dict(source_position="5511", item_code="FAS-SCR-TAP-PAN-8#1\"", uom="PACK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="8 x 1 PH Self Tapping Screw pan head (20PCS/PCK) - sibling of pos 3449 query set. Commodity pan-head self-tappers sold unbranded by all MY fastener dealers/marketplaces. No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="4524", item_code="FAS-RIV-PAT-1/8\"X1/4\"-PCK", uom="PCK",
         official_product_page="https://soongwung.com/product/jaguar-blind-rivet/",
         official_image_url="https://soongwung.com/wp-content/uploads/2024/02/C72.png",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="catalogue PCK 20PCS retail pack; source sells per-size boxes - packing granularity differs, same item",
         rights_status="needs_permission",
         reason="Blind Rivet Jaguar 1/8 x 1/4 (20PCS/PCK) - sibling of pos 3999. p:hardwarehouse.com.my/product/264/Jaguar-Blind-Rivet/ size list literally includes '1/8\" x 1/4\"' ('Jaguar Blind Rivet... Made in Malaysia'); p:soongwung.com/product/jaguar-blind-rivet/ opened: diameters incl 1/8\"(3.2MM), product photo C72.png saved. No Jaguar rivets OEM site anywhere -> dealer pages acceptable. Size proven via page text; aluminium finish unproven -> B.",
         human_action=""),
    dict(source_position="5512", item_code="FAS-SCR-ZPH-DSMHO516", uom="PCS",
         official_product_page="https://www.homepro.com.my/p/1059714",
         official_image_url="https://statice.homepro.co.th/homepromy/ART_IMAGE/10/597/1059714/1000x1000/09052025_1059714$Imagec1.jpg",
         researcher_decision="pending", match_confidence="B", finish_exact="yes", model_exact="yes",
         uom_assessment="catalogue 20PCS/PCK matches HomePro 20S pack",
         rights_status="needs_permission",
         reason="Sr Zph Self Drilling Screw (20PCS/PCK) DSM-HO516 (=#10x5/8 ZPH hex head). q:\"DSM-HO516\" self drilling screw zinc -> p:homepro.com.my/p/1059714 opened: 'AMAN ZF SELF DRILL SCREW 516 20S DSM-HO516', SKU 1059714, og:image 1000px saved; marketplace listings show same code under 'MK BRAND': 'DSM-HO516 #10 X 5/8 ZPH', subplace spec 'Brand: MK, Product Code: DSM-HO516, Size #10 X 5/8 ZPH'. Brand ambiguity MK vs AMAN on the exact-code page and no OEM site for either screw line -> pending B (model+ZPH finish proven by listings/HomePro title).",
         human_action=""),
    dict(source_position="3955", item_code="PIP-HDPE-32MM-1\"", uom="MTR",
         official_product_page="https://nyhardware.com.my/product/32mm-x-100m-hdpe-pn125-pipe-sirim-pe100",
         official_image_url="https://nyhardware.com.my/my_asset/products/plumbing-buildings/pipe/HDPE/HDPE-pn12.5.png",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="catalogue MTR vs source per-100M coil - same pipe, length granularity differs",
         rights_status="needs_permission",
         reason="PN12.5 x 100M HDPE Pipe SIRIM 32MM. q:HDPE pipe PN12.5 32mm SIRIM 100M roll Malaysia -> p:nyhardware.com.my/product/32mm-x-100m-hdpe-pn125-pipe-sirim-pe100 opened: '32MM X 100M HDPE PN12.5 PIPE PE100 [BBB] SIRIM' with dedicated product asset HDPE-pn12.5.png saved; p:mkhardware.com.my productid 6391495 '32MM X 100M HDPE PIPE PE100 (PN12.5) (SIRIM)' and p:clhardware.com same spec, Brand filter BBB/HANSEN. BBB = Malaysian PE100 pipe maker; no crawlable BBB official SKU page found -> MY dealer pages acceptable. All specs (32mm/100M/PN12.5/SIRIM/black) proven by titles/text -> B.",
         human_action=""),
    dict(source_position="3306", item_code="WAS-TAP-PAI", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Washi Tape 24MMX15M. q:washi tape 24mm 15m Malaysia stationery; q:washi masking tape decorative Malaysia supplier -> consumer craft tapes at bookstores/marketplaces, no hardware-brand OEM page; 'PAI' likely shop abbreviation. Commodity item. No OEM page identifiable. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3907", item_code="ABR-PAP-621-541", uom="SHT",
         researcher_decision="pending", match_confidence="C", finish_exact="no", model_exact="no",
         rights_status="unknown",
         reason="EWD Hand Sanding Sheet G1200 - sibling of pos 3278/3465/3881/3969/3970. Same query set: no EWD-branded page anywhere; identical-spec wet/dry sheets sold by MY abrasive suppliers under TOA/Nitto/generic brands. EWD = untraceable local importer initials -> pending C generic_unbranded.",
         human_action=""),
    dict(source_position="5905", item_code="FAS-SCR-TAP-PAN-6#3/4\"", uom="PACK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="6 X3/4 Self Tapping Screw pan head (20PCS/PCK) - sibling of pos 5511 query set. Commodity pan-head self-tappers sold unbranded everywhere. No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="4246", item_code="WAL-PLU-S/S-CC227-M10X80MM", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="S/steel Wall Plug K103-304 M10X80MM CC227 - sibling of pos 4732. q:\"K103-304\" OR \"CC227\" stainless wall plug M10 Malaysia -> zero hits for either code (same as CC226); nearest products are unbranded SUS304 sleeve anchors at MY dealers. Supplier internal codes, untraceable. generic_unbranded + code_untraceable -> reject.",
         human_action=""),
    dict(source_position="3915", item_code="FAS-SCR-TAP-CSK-6#2\"", uom="PACK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="6 X2 CSK Self Tapping Screw flat head (10PCS/PCK) - sibling of pos 3646/5548/3733/3181 query set. Commodity unbranded screws, no OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="2730", item_code="ELE-BUL-C7-E12-MINI", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="C7 E12 Mini Candle Bulb (clear). q:C7 E12 candle bulb clear Malaysia; q:night light bulb C7 E12 supplier -> commodity indicator/night-light bulbs sold unbranded at MY electrical dealers/marketplaces (Sierra Plus BTG/ORANGE bulbs are different models); C7/E12 is a bulb-type designation not a model. No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    # ---------------- WAVE 8 ----------------
    dict(source_position="3969", item_code="ABR-PAP-621-534", uom="PCS",
         researcher_decision="pending", match_confidence="C", finish_exact="no", model_exact="no",
         rights_status="unknown",
         reason="G240 EWD Hand Sanding Sheet - sibling of pos 3278/3465/3881. Same query set: no EWD-branded page anywhere; identical-spec wet/dry sheets sold by MY abrasive suppliers under TOA/Nitto/generic. EWD = untraceable local importer initials -> pending C generic_unbranded.",
         human_action=""),
    dict(source_position="3970", item_code="ABR-PAP-621-535", uom="SHT",
         researcher_decision="pending", match_confidence="C", finish_exact="no", model_exact="no",
         rights_status="unknown",
         reason="G320 EWD Hand Sanding Sheet - sibling of pos 3278/3465/3881/3969. Same query set: no EWD-branded page anywhere -> pending C generic_unbranded.",
         human_action=""),
    dict(source_position="3863", item_code="FAS-RIV-PAT-1/8\"X3/4\"-PCK", uom="PCK",
         official_product_page="https://soongwung.com/product/jaguar-blind-rivet/",
         official_image_url="https://soongwung.com/wp-content/uploads/2024/02/C72.png",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="catalogue PCK 20PCS retail pack; source sells per-size boxes - packing granularity differs, same item",
         rights_status="needs_permission",
         reason="Blind Rivet Jaguar 1/8 x 3/4 (20PCS/PCK) - sibling of pos 3999/4524. p:hardwarehouse.com.my/product/264/Jaguar-Blind-Rivet/ size list literally includes '1/8\" x 3/4\"'; p:soongwung.com/product/jaguar-blind-rivet/ opened: diameters incl 1/8\"(3.2MM), photo C72.png saved. No Jaguar rivets OEM site anywhere -> dealer pages acceptable. Size proven via text; finish unproven -> B.",
         human_action=""),
    dict(source_position="3646", item_code="FAS-SCR-TAP-CSK-6#2-1/2\"", uom="PACK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="6 x 2-1/2 CSK Self Tapping Screw flat head (10PCS/PCK) - sibling of pos 5548/3733/3181. Commodity unbranded screws, no OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="6054", item_code="SOC-BOX-28-13A", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="GI Socket Box 28X13A. q:GI conduit socket box 28mm Malaysia; q:GI junction box 13A conduit -> galvanised iron conduit boxes sold unbranded by MY electrical dealers/marketplaces. No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3858", item_code="BRA-S/S-L-85383", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Stainless Steel L Bracket 85383-85X85. q:\"85383\" stainless steel L bracket 85x85 Malaysia -> zero hits for the code; commodity SS L brackets at hommit/mkhardware/cheekuan (mfr) carry their own codes only. 85383 supplier-internal, untraceable. No OEM page. generic_unbranded + code_untraceable -> reject.",
         human_action=""),
    dict(source_position="5258", item_code="FAS-SCR-TAP-CSK-10#2\"", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="10 x 2 CSK Self Tapping Screw flat head (10PCS/PCK) - sibling of pos 3646 query set. Commodity unbranded screws, no OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="5259", item_code="FAS-SCR-ZPH-DSMHO520", uom="PCS",
         official_product_page="https://www.homepro.com.my/p/1059715",
         official_image_url="https://statice.homepro.co.th/homepromy/ART_IMAGE/10/597/1059715/1000x1000/09052025_1059715$Imagec1.jpg",
         researcher_decision="pending", match_confidence="B", finish_exact="yes", model_exact="yes",
         uom_assessment="catalogue 20PCS/PCK matches HomePro 20S pack",
         rights_status="needs_permission",
         reason="Sr Zph Self Drilling Screw (20PCS/PCK) DSM-HO520 (=#12x1 ZPH sibling of DSM-HO516). Same query set as pos 5512: p:homepro.com.my/p/1059715 'AMAN ZF SELF DRILL SCREW 526 20S DSM-HO520' SKU 1059715 og:image saved; marketplace 'MK BRAND DSM-HO520' listings confirm the DSM-HO52x series codes (ZPH zinc-plated hex-head self-drillers). Brand ambiguity MK vs AMAN; no OEM site for either screw line -> pending B.",
         human_action=""),
    dict(source_position="2727", item_code="BRU-SPO-B3PCS", uom="PKT",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="3M 213 Scouring Sponge Pad W/ab 3'S (kh SB1200775). q:3M Scotch-Brite 213 scouring pad sponge -> official 3M/scotch-brite catalogues list scour pads/sponges numbered 74/96/105/2000/2020/86/88/A21 etc.; NO '213' SKU exists in any 3M market catalogue. '213' + kh SB1200775 read as shop-internal codes for repacked generic sponge pads. Model untraceable against OEM range -> reject.",
         human_action=""),
    dict(source_position="4893", item_code="FAS-SCR-CSK-3\" X 8G-PCK", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Sr Csk Tapping Screw 3 x 8G (10PCS/PCK) - sibling of pos 2931 query set. Commodity countersunk tapping screws, unbranded everywhere. No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    # ---------------- WAVE 9 ----------------
    dict(source_position="5317", item_code="NAI-CON-GAL-2.1/2\"-PCK", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="2-1/2 Galvanised Steel Nail (20PCS/PCK). q:galvanised wire nail 2.1/2 inch Malaysia pack -> commodity common nails sold loose/repacked at all MY hardware dealers (chentat ACE Brand nails category is brand-level only). No OEM SKU page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3445", item_code="BNW-BOL-SS304-M10-35MM", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="SS 304 Bolt M10x35MM - sibling of pos 3308/3153 query set (DIN931 SS304 unbranded commodity). No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="4257", item_code="FAS-RIV-PAT-1/8\"X5/16\"-PCK", uom="PCK",
         official_product_page="https://soongwung.com/product/jaguar-blind-rivet/",
         official_image_url="https://soongwung.com/wp-content/uploads/2024/02/C72.png",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="catalogue PCK 20PCS retail pack; source sells per-size boxes - packing granularity differs, same item",
         rights_status="needs_permission",
         reason="Blind Rivet Jaguar 1/8 x 5/16 (20PCS/PCK) - sibling of pos 3999/4524/3863. p:hardwarehouse.com.my/product/264/Jaguar-Blind-Rivet/ size list literally includes '1/8\" x 5/16\"'; p:soongwung.com/product/jaguar-blind-rivet/ opened: diameters incl 1/8\"(3.2MM), photo C72.png saved. No Jaguar rivets OEM site anywhere -> dealer pages acceptable. Size proven via text; finish unproven -> B.",
         human_action=""),
    dict(source_position="5878", item_code="SOC-6MM-3WAY", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="PVC 3/4 3WAY Box - sibling of pos 4668/5963/6072 commodity conduit-box family, unbranded at MY dealers/marketplaces. No OEM page. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="2868", item_code="SPO-SCOTCH-BRITE-3M", uom="PCK",
         official_product_page="https://www.homepro.com.my/p/1031600",
         official_image_url="https://statice.homepro.co.th/homepromy/ART_IMAGE/10/316/1031600/1000x1000/09052025_1031600$Imagec1.jpg",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="catalogue 3PCS pack vs HomePro 5PC/PACK and Lotus's 3S variant - same SKU family, pack granularity differs",
         rights_status="needs_permission",
         reason="3M Scotch Brite 31B Scouring Pad. q:\"Scotch-Brite\" \"31B\" scouring pad -> p:homepro.com.my/p/1031600 'SCOTCH BRITE SCOURING PAD 31-B 5PC/PACK' with description quoting the Scotch-Brite Heavy Duty Scouring Pad family text; og:image 1000px saved; p:myaeon2go 'Scotch Brite Scouring Pad (31-B)'; p:lotuss.com.my 'SCOURING PAD 31B 3S' corroborating the catalogue's 3PCS pack; mqsupplies 31-B Heavy Duty. No 3M.com OEM page exists for the SEA-market 31-B SKU (US catalogue carries 86/88/96 etc.) -> retailer pages acceptable under no-OEM rule. Model 31B proven by multiple page texts; green pad colour implied by image but not stated in text -> B.",
         human_action=""),
    dict(source_position="3724", item_code="BNW-BOL-SS304-M10-25MM", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="SS 304 Bolt M10x25MM - sibling of pos 3308/3153/3445 query set. Commodity unbranded DIN fastener, no OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3223", item_code="ELE-T5-4-CIELO-W/W", uom="PCS",
         official_product_page="https://cimalighting.com.my/product/cielo-gen2-t5-led-batten-2ft-3ft-4ft-10w-14w-18w-sirim-cetificated",
         official_image_url="https://cdn1.sgliteasset.com/eluxelig/images/product/product-5938586/bTvNUfqm678492d232a63_1736741586.jpg",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="PCS correct per fitting",
         rights_status="needs_permission",
         reason="Cielo T5 LED Fitting 4FT 18W WW(=warmwhite 3000K, internal code WW-830) - sibling of pos 2884. Same evidence set: CIELO GEN2 T5 LED BATTEN [2FT/3FT/4FT][10W/14W/18W] SIRIM certified on brand-owner webstore cimalighting.com.my ('Brand: Cielo', CIMA Lighting), second gallery asset bTvNUfqm...jpg saved; colour temperature selectable incl WarmWhite 3000K per Shopee/Lazada GEN2 listings ('Colour Temperature: Daylight 6000K / CoolWhite 4000K / WarmWhite 3000K'). WW variant not pinned in static image -> B.",
         human_action=""),
    dict(source_position="3163", item_code="SANDEX-VEL-PAD-M10-4\"", uom="PCS",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Sandex 4in Velcro Backing Pad M10. q:\"Sandex\" velcro backing pad M10 4 inch Malaysia abrasive -> zero SANDEX-brand hits anywhere; commodity velcro backing pads M10 sold unbranded at aurous.com.my, ghhardware.com.my, marketplaces. SANDEX = untraceable local importer initials. No OEM page. generic_unbranded + brand_untraceable -> reject.",
         human_action=""),
    dict(source_position="4143", item_code="PIP-HDPE-25MM-PN12.5", uom="LTH",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="3M HDPE Pipe Non-SIRIM x 25MM PN12.5. Same query set as pos 3955: HDPE PE100 PN12.5 coils sold by clhardware/mkhardware under BBB/HANSEN brands, but this row is explicitly NON-SIRIM grade = lowest-commodity coil sold unbranded per length; no brand/OEM page identifiable for non-certified stock. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="2659", item_code="WAL-PLU-JWP-6MM", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Jaw Wall Plug 6MM (10PCS/PCK). q:\"jaw wall plug\" OR \"jwp\" wall plug 6mm Malaysia -> no JAW/JWP-branded plug page exists; commodity 6mm PVC wall plugs sold in bars/packs everywhere (globalproofficial red plugs, tulips PVC Wall Plug, culmi grey sheets). JWP = supplier code for jaw-type plug, untraceable to a brand. No OEM page. generic_unbranded + code_untraceable -> reject.",
         human_action=""),
    # ---------------- WAVE 10 ----------------
    dict(source_position="5009", item_code="PIP-UPVC-5255-1.1/4\"", uom="MTR",
         official_product_page="https://unimechengineering.com.my/product/upvc-pipe-2/",
         official_image_url="https://unimechengineering.com.my/wp-content/uploads/2022/03/UPCV-Pipe-BS4255-1.jpg",
         researcher_decision="candidate", match_confidence="B", finish_exact="no", model_exact="yes",
         uom_assessment="MTR correct; pipe supplied in 6M lengths per page",
         rights_status="needs_permission",
         reason="1 1/4(32MM) x 6M UPVC Pipe BS5255 - sibling of pos 3872. p:unimechengineering.com.my/product/upvc-pipe-2/ opened: 'Material: UPVC, Spec: BS5255, Length: 6 meter, Size: 32 - 50mm' -> 32mm (=1-1/4in) inside stated range, BS5255 and 6M literal; same white SWV pipe photo. BINA Plastic mfr catalogue (sanifix link) corroborates MS1063/BS5255 family with 36mm nominal 1-1/4 size. Catalogue brand blank commodity-spec item -> candidate B.",
         human_action=""),
    dict(source_position="3759", item_code="FAS-SCR-P/H-5/8\" X 8#", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Sr P/h Self Drilling Screw 5/8 x 8 (20PCS/PCK) - sibling of pos 3449 query set ('Sr'=shop prefix). Commodity pan-head self-drillers, unbranded at MY dealers/marketplaces. No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="3706", item_code="FAS-SCR-F/H-5/8\" X 8#", uom="PCK",
         researcher_decision="reject", match_confidence="R", finish_exact="no", model_exact="no",
         rights_status="no_asset",
         reason="Sr F/h Self Drilling Screw 5/8 x 8 (20PCS/PCK) - sibling of pos 3283/3449/3759 query set. Commodity flat-head self-drillers, unbranded everywhere. No OEM page possible. generic_unbranded -> reject.",
         human_action=""),
    dict(source_position="6742", item_code="FAS-SCR-DRY-BLA-6#1\"", uom="PCK",
         official_product_page="https://www.sionghua.com.sg/product/image126/",
         official_image_url="https://www.sionghua.com.sg/wp-content/uploads/2021/04/BLACK-DRYWALL-SCREWS-1.jpg",
         researcher_decision="pending", match_confidence="B", finish_exact="yes", model_exact="yes",
         rights_status="needs_permission",
         reason="Hunter/bk Drywall Screw 6# x 1 (20PCS/PCK) - sibling of pos 4313/3092/6743. p:sionghua.com.sg/product/image126/ opened: 'HUNTER DRYWALL SCREW (BLACK) AVAILABLE IN: 6 x 3/4\", 6 x 1\", 6 x 1 1/4\", 6 x 1 1/2\", 6 x 1 3/4\", 6 x 2\"' -> colour BLACK + exact size 6x1 both literally enumerated; black screws photo saved. No Hunter OEM site exists anywhere and no MY non-marketplace dealer page found for Hunter black 6x1 (source is SG hardware dealer); largest source image is 413x346 (below 500px bar, low_res noted) -> pending B.",
         human_action=""),
]


def main():
    brief_path = OUT.parent / "shard-03-brief.txt"
    brief = []
    with brief_path.open(encoding="utf-8") as fh:
        for line in fh.read().splitlines()[1:]:
            if line.strip():
                brief.append(line.split("|")[1])
    idx = {code: i for i, code in enumerate(brief)}
    seen = {}
    ordered = []
    for r in ROWS:
        code = r["item_code"]
        if code in seen:
            raise SystemExit(f"duplicate item_code {code}")
        seen[code] = True
        ordered.append(r)
    missing = [c for c in brief if c not in seen]
    extra = [r["item_code"] for r in ROWS if r["item_code"] not in idx]
    if missing or extra:
        raise SystemExit(f"missing={missing} extra={extra}")
    ordered.sort(key=lambda r: idx[r["item_code"]])

    with OUT.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=HEADER)
        w.writeheader()
        for r in ordered:
            w.writerow({k: r.get(k, "") for k in HEADER})
    print(f"wrote {len(ordered)} rows -> {OUT}")


if __name__ == "__main__":
    main()
