const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const state = { data: null, aisle: "all", query: "", available: false, band: "all", sort: "name", pinned: new Set() };
const el = { index: document.querySelector("#aisle-index"), wall: document.querySelector("#wall"), search: document.querySelector("#wall-search"), available: document.querySelector("#available-filter"), band: document.querySelector("#price-band"), sort: document.querySelector("#wall-sort"), count: document.querySelector("#result-count"), summary: document.querySelector("#active-summary"), empty: document.querySelector("#empty"), bench: document.querySelector("#compare-bench"), benchToggle: document.querySelector("#bench-toggle"), benchCount: document.querySelector("#bench-count"), benchItems: document.querySelector("#bench-items") };
const categoryName = (slug) => state.data.categories.find((category) => category.slug === slug)?.name ?? slug;
const stock = (product) => product.stock_quantity <= product.low_stock_threshold ? { low: true, text: `Low · ${product.stock_quantity}` } : { low: false, text: `${product.stock_quantity} in stock` };
function filtered() { const query=state.query.trim().toLowerCase(); return state.data.products.filter((product)=>{ const dollars=product.price_cents/100; const band=state.band==="all" || state.band==="under-100"&&dollars<100 || state.band==="100-400"&&dollars>=100&&dollars<=400 || state.band==="over-400"&&dollars>400; return (state.aisle==="all"||product.category_slug===state.aisle)&&(!query||product.name.toLowerCase().includes(query))&&(!state.available||product.stock_quantity>0)&&band; }).sort((a,b)=>state.sort==="price-asc"?a.price_cents-b.price_cents:state.sort==="price-desc"?b.price_cents-a.price_cents:state.sort==="featured"?Number(b.featured)-Number(a.featured)||a.id-b.id:a.name.localeCompare(b.name)); }
function renderIndex(){ const categories=state.data.categories.filter((category)=>category.slug!=="all"); el.index.innerHTML=categories.map((category,index)=>`<button class="aisle-tile" type="button" data-aisle="${category.slug}" aria-pressed="${state.aisle===category.slug}"><span class="index">${String(index+1).padStart(2,"0")}</span><span class="name">${category.name}</span><span class="count">${state.data.products.filter((product)=>product.category_slug===category.slug).length}</span></button>`).join(""); el.index.querySelectorAll("button").forEach((button)=>button.addEventListener("click",()=>{state.aisle=state.aisle===button.dataset.aisle?"all":button.dataset.aisle;render()})); }
function plate(product,index,size="standard"){ const s=stock(product), category=categoryName(product.category_slug), pinned=state.pinned.has(product.id); return `<article class="plate ${size}"><a class="image-well" href="#product-${product.id}" aria-label="Open ${product.name}"><span class="plate-number">P-${String(index+1).padStart(2,"0")}</span><span class="image-copy">Product image is not available yet.</span></a><div class="plate-copy"><div class="catalogue-label">Catalogue label · <b>${product.tone}</b></div><a class="plate-name" href="#product-${product.id}">${product.name}</a></div><div class="plate-ledger"><div class="ledger-cell"><span>PRICE</span><b class="price">${money.format(product.price_cents/100)}</b></div><div class="ledger-cell"><span>STOCK</span><b class="stock${s.low?" low":""}">${s.text}</b></div><div class="ledger-cell"><span>AISLE</span><b>${category}</b></div></div><div class="plate-actions"><a href="#product-${product.id}">Open product</a><button type="button">Add to cart</button><button class="pin" type="button" data-pin="${product.id}" aria-pressed="${pinned}">${pinned?"Pinned":"Pin to compare"}</button></div></article>`; }
const atmosphere = `<aside class="atmosphere"><div class="atmosphere-copy"><span>AISLE ATMOSPHERE</span><h2>Build the room, not just the list.</h2><p>Category imagery only. Does not show the exact product sold.</p></div></aside>`;
function renderWall(){ const products=filtered(); const pieces=[]; products.forEach((product,index)=>{ if(index===0) pieces.push(plate(product,index,"large")); else if(index===1){pieces.push(plate(product,index,"small"));pieces.push(atmosphere)} else pieces.push(plate(product,index)); }); el.wall.innerHTML=pieces.join(""); el.wall.hidden=!products.length; el.empty.hidden=!!products.length; el.count.textContent=`${products.length} ${products.length===1?"product":"products"} on wall`; el.summary.textContent=state.aisle==="all"?"All aisles":categoryName(state.aisle); el.wall.querySelectorAll("[data-pin]").forEach((button)=>button.addEventListener("click",()=>{const id=Number(button.dataset.pin);state.pinned.has(id)?state.pinned.delete(id):state.pinned.add(id);renderWall();renderBench()})); }
function renderBench(){ const products=state.data.products.filter((product)=>state.pinned.has(product.id)).slice(0,3); el.benchCount.textContent=`${products.length} PINNED`; el.benchItems.innerHTML=products.map((product)=>{const s=stock(product);return `<div class="bench-item"><b>${product.name}</b><p><span>${money.format(product.price_cents/100)}</span><span>${s.text}</span><span>${categoryName(product.category_slug)}</span></p></div>`}).join(""); if(!products.length){el.bench.classList.remove("open");el.benchToggle.setAttribute("aria-expanded","false")} }
function render(){renderIndex();renderWall();renderBench()}
document.querySelector(".search").addEventListener("submit",(event)=>event.preventDefault());
el.search.addEventListener("input",(event)=>{state.query=event.currentTarget.value;renderWall()});el.available.addEventListener("change",(event)=>{state.available=event.currentTarget.checked;renderWall()});el.band.addEventListener("change",(event)=>{state.band=event.currentTarget.value;renderWall()});el.sort.addEventListener("change",(event)=>{state.sort=event.currentTarget.value;renderWall()});el.benchToggle.addEventListener("click",()=>{const open=el.bench.classList.toggle("open");el.benchToggle.setAttribute("aria-expanded",String(open))});
fetch("/catalogue.json").then((response)=>{if(!response.ok)throw new Error(`Catalogue request failed: ${response.status}`);return response.json()}).then((data)=>{state.data=data;render()}).catch((error)=>{console.error(error);el.empty.hidden=false;el.empty.textContent="Catalogue unavailable."});
