#!/usr/bin/env python3
"""Build shard-0151-0250.csv for slot E2 (ordinals 151..250)."""
import csv

OUT = r"C:\Users\DELL\OneDrive\Desktop\ekoway hardware website\online-shopping-platform\catalogue\ai-inbox\opencode-recover\loop-state\chat-01\shard-0151-0250.csv"

HDR = ["source_position","item_code","uom","official_product_page","official_image_url",
       "researcher_decision","match_confidence","finish_exact","model_exact",
       "uom_assessment","rights_status","reason","human_action"]

BLOCK = "[websearch/exa 429-blocked entire session, retries at ~5-20min spacing]"

# (pos, code, uom, decision, conf, fin, mod, uom_a, rights, reason, human)
ROWS = [
(4360,"CAP-02.5UF-415V-CBB61","PCS","reject","R","no","no","pcs_ok","no_asset",
 "tier2 start (ledger=1). q:'CBB61 capacitor 2.5UF 415V Malaysia' "+BLOCK+"; CBB61 run capacitor is commodity OEM-less part, catalogue model token '2.5UF'=rating not mfr model; 'Blnch/sh-po' packaging marks not an OEM site lead; generic_unbranded, prior reject upheld","shoot in-store"),
(3282,"FAS-SCR-F/H-1 1/2\" X 8#","PKT","reject","R","no","no","pkt_of_20_ok","no_asset",
 "tier2 start. q:'SR self drilling screw flat head 8 x 1-1/2 Malaysia' "+BLOCK+"; SR=local repack fastener brand, no official site discoverable in ledger probes; size-normalisation variants (1-1/2in/38mm) yield no OEM page concept; commodity generic_unbranded, prior reject upheld","shoot in-store"),
(3685,"FAS-SCR-TAP-CSK-8#2\"","PACK","reject","R","no","no","pack_of_10_ok","no_asset",
 "tier2 start. q:'8x2 csk self tapping screw flat head 10pcs Malaysia' "+BLOCK+"; commodity wood-screw pack generic_unbranded no OEM page concept; prior reject upheld","shoot in-store"),
(4083,"CUT-ELE-ESS410D","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'\"Gold Elephant\" ESS410D cutting disc 4 inch' + variant '\"Gold Elephant\" cutting disc Malaysia' "+BLOCK+" both blocked; Gold Elephant is a real abrasive disc mfr brand (MY/SG distribution) so OEM page may exist; cannot verify this session","retry_when_search_restored"),
(3986,"SWI-SOC-ULT-M0813W","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'\"Ultra\" M0813W 13A switched socket Malaysia' "+BLOCK+"; Ultra=Malaysian switch brand (ULTRA Electrical Industries) with likely official site; prior candidate needs page+bytes proof, unverifiable while search down","retry_when_search_restored"),
(4156,"BRA-S/S-L-65383","PCS","reject","R","no","no","pcs_ok","no_asset",
 "tier2 start. q:'stainless steel L bracket 65x65mm Malaysia' "+BLOCK+"; plain S/S angle bracket commodity generic_unbranded, 65383=supplier sku not mfr model; prior reject upheld","shoot in-store"),
(3226,"FAS-SCR-CSK-1 1/2\" X 8G","PCK","reject","R","no","no","pck_of_20_ok","no_asset",
 "tier2 start. q:'SR csk tapping screw 1-1/2 x 8G 20pcs Malaysia' "+BLOCK+"; SR local repack, commodity countersunk wood screw pack generic_unbranded; prior reject upheld","shoot in-store"),
(3309,"BNW-BOL-SS304-M12-25MM","PCS","reject","R","no","no","pcs_ok","no_asset",
 "tier2 start. q:'SS304 hex bolt M12x25 DIN931 Malaysia' "+BLOCK+"; commodity A2 hex bolt generic_unbranded no OEM page concept; prior reject upheld","shoot in-store"),
(3814,"FAS-SCR-CSK-1\" X 6G-PCK","PCK","reject","R","no","no","pck_of_20_ok","no_asset",
 "tier2 start. q:'SR csk tapping screw 1 x 6G 20pcs Malaysia' "+BLOCK+"; commodity csk tapping screw pack generic_unbranded; prior reject upheld","shoot in-store"),
(6667,"NAI-CON-GAL-1\"-PCK","PCK","reject","R","no","no","pck_of_20_ok","no_asset",
 "tier2 start. q:'galvanised steel nail 1 inch 20pcs Malaysia' "+BLOCK+"; commodity nail pack generic_unbranded; prior reject upheld","shoot in-store"),
(3068,"BRO-PLA-SB9226","PCS","reject","R","no","no","pcs_ok","no_asset",
 "tier2 start. q:'plastic broom SB9226 Malaysia' "+BLOCK+"; unbranded import broom, 180G weight token not mfr model; no OEM site concept; prior reject upheld","shoot in-store"),
(3861,"ELE-ADA-MS-PT13","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'Morries MS-PT13 travel adaptor' + 'Morries electrical Malaysia official' "+BLOCK+"; Morries=MY electrical accessories brand (Morries Trading) likely official site; prior candidate unverifiable while search down","retry_when_search_restored"),
(2774,"DOR-HIN-STE-CLO-5/8\"","PCS","reject","R","no","no","pcs_ok","no_asset",
 "tier2 start. q:'soft close hinge 5/8 inch overlay Malaysia' "+BLOCK+"; generic import hinge no brand/model OEM; HINGES-5/8=size token; prior reject upheld","shoot in-store"),
(2959,"TOO-ELE-TESW0183","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'tester pen W0183 voltage Malaysia' "+BLOCK+"; W0183 looks like a mfr model but maker unknown; need search to attribute; unverifiable while search down","retry_when_search_restored"),
(5095,"FAS-SCR-P/H-1\" X 8#","PCK","reject","R","no","no","pck_of_20_ok","no_asset",
 "tier2 start. q:'SR pan head self drilling screw 8 x 1 20pcs Malaysia' "+BLOCK+"; SR repack commodity tek screw generic_unbranded; prior reject upheld","shoot in-store"),
(3217,"WIN-HOO-PIN-8430","PCK","reject","R","no","no","pck_of_10_ok","no_asset",
 "tier2 start. q:'SR pin hook pleat hook curtain 8430 Malaysia' "+BLOCK+"; SR repack curtain hook commodity generic_unbranded; prior reject upheld","shoot in-store"),
(4019,"WOO-SQU-08'","PCS","reject","R","no","no","pcs_ok_8ft_length","no_asset",
 "tier2 start. q:'wood square list 8ft S4S Malaysia timber' "+BLOCK+"; raw timber moulding commodity generic_unbranded; prior reject upheld","shoot in-store"),
(3834,"FAS-SCR-F/H-3/4\" X 8#","PCK","reject","R","no","no","pck_of_20_ok","no_asset",
 "tier2 start. q:'SR flat head self drilling screw 3/4 x 8 Malaysia' "+BLOCK+"; SR repack commodity generic_unbranded; prior reject upheld","shoot in-store"),
(6193,"FAS-SCR-TAP-CSK-8#3/8\"-PCK","PCK","reject","R","no","no","pck_of_20_ok","no_asset",
 "tier2 start. q:'8 x 3/8 csk self tapping screw 20pcs Malaysia' "+BLOCK+"; commodity small csk screw pack generic_unbranded; prior reject upheld","shoot in-store"),
(3370,"FAS-SCR-DRY-BLA-6#1-1/2\"BOX","BOX","reject","R","no","no","box_ok","no_asset",
 "tier2 start. q:'Hunter drywall screw black 6 x 1-1/2 box Malaysia' "+BLOCK+"; Hunter/bk=local repack drywall-screw house brand, no OEM site discoverable in ledger; commodity; prior reject upheld","shoot in-store"),
(3406,"FAS-SCR-DRY-BLA-6#3/4\"-BOX","BOX","reject","R","no","no","box_ok","no_asset",
 "tier2 start. q:'Hunter black drywall screw 6 x 3/4 box Malaysia' "+BLOCK+"; Hunter/bk local repack house brand no OEM site; commodity drywall screw box; prior reject upheld","shoot in-store"),
(2841,"GER-PLUG-BPM6A","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'NGK BPM6A spark plug Malaysia' (+site ngkntk.com.my probe p:https://www.ngkntk.com.my/ transport-error unreachable this session) "+BLOCK+"; NGK is real OEM (NGK NTK Malaysia); official page plausible but unverifiable while search down and domain unreachable from here","retry_when_search_restored"),
(4465,"WAL-PLU-S/S-80MM","PCS","reject","R","no","no","pcs_ok","no_asset",
 "tier2 start. q:'304 stainless wall plug M10x80mm Malaysia' "+BLOCK+"; commodity anchor plug generic_unbranded; prior reject upheld","shoot in-store"),
(4149,"SHH-SINKER-NO.1/2","PCK","reject","R","no","no","pck_of_2_ok","no_asset",
 "tier2 start. q:'fishing sinker weight no 1/2 Malaysia' "+BLOCK+"; cast lead sinker generic_unbranded fishing tackle; no OEM page concept; prior reject upheld","shoot in-store"),
(3662,"FAS-SCR-TAP-CSK-6#3\"","PACK","reject","R","no","no","pack_of_10_ok","no_asset",
 "tier2 start. q:'6 x 3 csk self tapping screw flat head 10pcs Malaysia' "+BLOCK+"; commodity generic_unbranded; prior reject upheld","shoot in-store"),
(3707,"FAS-SCR-TAP-CSK-6#1-1/2\"","PACK","reject","R","no","no","pack_of_20_ok","no_asset",
 "tier2 start. q:'6 x 1-1/2 csk self tap screw 20pcs Malaysia' "+BLOCK+"; commodity generic_unbranded; prior reject upheld","shoot in-store"),
(6021,"FAS-SCR-TAP-CSK-6#1\"","PACK","reject","R","no","no","pack_of_20_ok","no_asset",
 "tier2 start. q:'6 x 1 csk self tapping screw flat head 20pcs Malaysia' "+BLOCK+"; commodity generic_unbranded; prior reject upheld","shoot in-store"),
(2746,"ELE-D/L-PHL-59466-RD-6500K","SET","pending","C","unknown","unknown","set_ok","unknown",
 "tier2 start. q:'Philips Meson LED downlight 59466' + 'Philips 59466500 Malaysia' "+BLOCK+" ; p:https://www.philips.com.my/c-p/59466500/meson-led-downlight ->404 guess rejected; Philips Meson is real OEM product line, need true PURL; unverifiable while search down","retry_when_search_restored"),
(3150,"VAL-BAL-VIP-343-12MM","PCS","pending","C","unknown","unknown","pcs_ok_half_inch","unknown",
 "tier2 start. q:'VIP full bore ball valve PN25 1/2 brass Malaysia' "+BLOCK+"; VIP=MY plumbing brand (VIP valves) possible official/distributor pages; unverifiable while search down","retry_when_search_restored"),
(3731,"FAS-SCR-F/H-1\" X 8#","PKT","reject","R","no","no","pkt_of_20_ok","no_asset",
 "tier2 start. q:'SR flat head self drilling screw 8 x 1 Malaysia' "+BLOCK+"; SR repack commodity generic_unbranded; prior reject upheld","shoot in-store"),
(2988,"DOR-ROL-GAT-75MM-V70","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'V70 gate roller 75mm V groove Malaysia' "+BLOCK+"; V70 could be mfr model (gate roller); attribution unknown; unverifiable while search down","retry_when_search_restored"),
(3385,"SWI-SOC-ULT-M021MG","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'\"Ultra\" M021MG 16A 2 gang switched socket Malaysia' "+BLOCK+"; Ultra MY switch brand likely official site; prior candidate unverifiable while search down","retry_when_search_restored"),
(3942,"BAT-ENE-MINI-A27","PCK","pending","C","unknown","unknown","pck_of_1_bp1_ok","unknown",
 "tier2 start. q:'Energizer A27 battery BP1' + 'Energizer A27 12V specialty' "+BLOCK+"; Energizer real OEM energizer.com product exists; need page+bytes proof; unverifiable while search down","retry_when_search_restored"),
(4539,"SWI-ADA-TRA-ES288T","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'Eurosafe deluxe travel adaptor 308N ES288T Malaysia' "+BLOCK+"; brand attribution uncertain (DLX/Eurosafe local brands); unverifiable while search down","retry_when_search_restored"),
(3492,"CEILING-FRAME-35MM","PCS","reject","R","no","no","pcs_ok_12ft_length","no_asset",
 "tier2 start. q:'steel keel ceiling frame 35mm 12ft Malaysia' "+BLOCK+"; construction steel profile commodity generic_unbranded; prior reject upheld","shoot in-store"),
(4340,"CUT-KNI-HX338","BOX","pending","C","unknown","unknown","box_of_10_ok","unknown",
 "tier2 start. q:'NT Cutter replacement blade A80 10pcs box' "+BLOCK+"; NT Cutter=real Japanese OEM (nt-cutter.co.jp) but model mapping HX338/A80 unconfirmed; unverifiable while search down","retry_when_search_restored"),
(5393,"FIT-HDPE-ADA-FEM-20MMX3/4\"","PCS","reject","R","no","no","pcs_ok","no_asset",
 "tier2 start. q:'HDPE adaptor female 20mm x 3/4 Malaysia' "+BLOCK+"; commodity compression fitting generic_unbranded; prior reject upheld","shoot in-store"),
(5478,"FIT-UPVC-BEN-ELB-45-32MM","PCS","reject","R","no","no","pcs_ok","no_asset",
 "tier2 start. q:'uPVC bend elbow 32mm 45 degree solvent Malaysia' "+BLOCK+"; commodity pipe fitting generic_unbranded; prior reject upheld","shoot in-store"),
(2775,"ELE-D/L-PHL-59467-SQ-4000K","SET","pending","C","unknown","unknown","set_ok","unknown",
 "tier2 start. q:'Philips Meson 59467 square LED downlight 4000K' "+BLOCK+"; Philips OEM line; need true PURL; unverifiable while search down","retry_when_search_restored"),
(3424,"FAS-SCR-DRY-WHI-6#2\"-BOX","BOX","reject","R","no","no","box_ok","no_asset",
 "tier2 start. q:'Hunter white drywall screw 6 x 2 box Malaysia' "+BLOCK+"; Hunter/wh local repack house brand no OEM site; commodity; prior reject upheld","shoot in-store"),
(2923,"LOC-CZS-L40MM","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'CZS 360 padlock 40mm Malaysia' "+BLOCK+"; CZS=padlock brand of uncertain origin; possible distributor pages; unverifiable while search down","retry_when_search_restored"),
(3985,"SWI-ADA-MS-PT06","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'Morries MS-PT06 travel adaptor Japan USA' "+BLOCK+"; Morries MY brand likely official; prior candidate unverifiable while search down","retry_when_search_restored"),
(3467,"BNW-B&N-RBN-220","PCK","reject","R","no","no","pck_of_5_ok","no_asset",
 "tier2 start. q:'GI bolt and nut 1/4 x 2 ribbed 5pcs Malaysia' "+BLOCK+"; commodity roofing-bolt pack generic_unbranded (Sr repack); prior reject upheld","shoot in-store"),
(3499,"FAS-SCR-DRY-BLA-6#2\"BOX","BOX","reject","R","no","no","box_ok","no_asset",
 "tier2 start. q:'Hunter black drywall screw 6 x 2 box Malaysia' "+BLOCK+"; Hunter/bk local repack house brand; commodity; prior reject upheld","shoot in-store"),
(3404,"ELE-SOL-TIN100250G","PCS","pending","C","unknown","unknown","pcs_250g_reel_ok","unknown",
 "tier2 start. q:'Vison soldering wire 0.8mm 250g Malaysia' "+BLOCK+"; Vison=solder brand seen on MY marketplaces, OEM site unknown; unverifiable while search down","retry_when_search_restored"),
(2728,"DOR-HAN-CH608-NA-L","PCS","pending","C","unknown","unknown","pcs_left_hand_ok","unknown",
 "tier2 start. q:'CH608 casement window handle left Malaysia' "+BLOCK+"; CH608 may be mfr model for aluminium-window handle; attribution unknown; unverifiable while search down","retry_when_search_restored"),
(2853,"ADH-TAP-VIP-2510","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'VIP PTFE thread seal tape VIP-2510 Malaysia' "+BLOCK+"; VIP plumbing brand possible official/distributor; unverifiable while search down","retry_when_search_restored"),
(3587,"FAS-RIV-PAT-5/32X3/4-PCK","PCK","pending","C","unknown","unknown","pck_of_20_ok","unknown",
 "tier2 start. q:'Jaguar blind rivet 5/32 x 3/4 20pcs Malaysia' "+BLOCK+"; Jaguar=blind-rivet brand sold in MY; OEM/distributor site possible; unverifiable while search down","retry_when_search_restored"),
(5293,"FIT-UPVC-BEN-ELB-45-50MM","PCS","reject","R","no","no","pcs_ok","no_asset",
 "tier2 start. q:'uPVC bend 50mm 45 degree Malaysia' "+BLOCK+"; commodity fitting generic_unbranded; prior reject upheld","shoot in-store"),
(4538,"SUP-ROL-WIN","PCK","pending","C","unknown","unknown","pck_of_25_ok","unknown",
 "tier2 start. q:'Super Airoller window roller 25pcs Malaysia' "+BLOCK+"; Airoller=screen-roller brand of uncertain origin; unverifiable while search down","retry_when_search_restored"),
(2637,"SWI-LAM-ADA-3041B22","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'B22 nylon lamp holder adaptor 3041 Malaysia' "+BLOCK+"; 3041B22 maybe mfr sku; attribution unknown; unverifiable while search down","retry_when_search_restored"),
(6602,"BNW-WAS-SPR-9MM","PCK","reject","R","no","no","pck_of_8_ok","no_asset",
 "tier2 start. q:'BSW spring washer 3/8 8pcs Malaysia' "+BLOCK+"; commodity washer pack generic_unbranded; prior reject upheld","shoot in-store"),
(4998,"ELE-PVC-CAS-3/4\"","LGTH","pending","C","unknown","unknown","length_6ft_ok","unknown",
 "tier2 start. q:'Kancil PVC casing 3/4 x 6ft Malaysia' "+BLOCK+"; Kancil=MY wiring-casing brand, distributor pages possible; unverifiable while search down","retry_when_search_restored"),
(4487,"SHH-SINKER-HOLE-NO.6","PCK","reject","R","no","no","pck_of_1_ok","no_asset",
 "tier2 start. q:'hole sinker fishing weight no 6 Malaysia' "+BLOCK+"; generic_unbranded tackle; prior reject upheld","shoot in-store"),
(3518,"FAS-SCR-DRY-WHI-6#1.1/4\"-BOX","BOX","reject","R","no","no","box_ok","no_asset",
 "tier2 start. q:'Hunter white drywall screw 6 x 1-1/4 box Malaysia' "+BLOCK+"; Hunter/wh local repack house brand; commodity; prior reject upheld","shoot in-store"),
(4890,"CAP-01.2UF-400V-BD","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'CPI capacitor Italy 400V 1.2uF fan motor' "+BLOCK+"; CPI(Italcap?) marking suggests Italian cap brand; attribution uncertain; unverifiable while search down","retry_when_search_restored"),
(2615,"CUT-BLA-M'MAN-F1X4\"","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'M-Man diamond blade F1X4 4 inch Malaysia' "+BLOCK+"; M'man blade brand uncertain; unverifiable while search down","retry_when_search_restored"),
(2636,"RAI-BOO-KRK-B39M","PAIR","pending","C","unknown","unknown","pair_size39_ok","unknown",
 "tier2 start. q:'rain shoes boots 6000BLK size 39 Malaysia Krork' "+BLOCK+"; brand/model garbled (KRK/B39M); unverifiable while search down","retry_when_search_restored"),
(3589,"FAS-SCR-DRY-BLA-6#1\"BOX","BOX","reject","R","no","no","box_ok","no_asset",
 "tier2 start. q:'Hunter black drywall screw 6 x 1 box Malaysia' "+BLOCK+"; Hunter/bk local repack house brand; commodity; prior reject upheld","shoot in-store"),
(4122,"SWI-SOC-ULT-M0813BW","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'\"Ultra\" M0813BW large rocker socket white Malaysia' "+BLOCK+"; Ultra MY switch brand; prior candidate unverifiable while search down","retry_when_search_restored"),
(3347,"IND-CAS-FIX-1.25\"","PCS","pending","C","unknown","unknown","caster_1_25in_ok","unknown",
 "tier2 start. q:'TPE fixed caster DL5 1.25 inch Malaysia' "+BLOCK+"; DL5 caster series attribution unknown; unverifiable while search down","retry_when_search_restored"),
(4580,"HOS-SPA-NOZ-C882","PCS","pending","C","unknown","unknown","nozzle_3_4_ok","unknown",
 "tier2 start. q:'C882 quick coupling nozzle 3/4 Malaysia' "+BLOCK+"; C882 model attribution unknown; unverifiable while search down","retry_when_search_restored"),
(3303,"TOO-ELE-TES-PEN-K1304","PCS","pending","C","unknown","unknown","pcs_ok","unknown",
 "tier2 start. q:'KAKC test pen K1304 Malaysia' "+BLOCK+"; KAKC/K1304 attribution unknown; unverifiable while search down","retry_when_search_restored"),
(5227,"DRI-BIT-SV003","PCS","pending","C","unknown","unknown","bit_65mm_ok","unknown",
 "tier2 start. q:'Sensui power bit double ended 65mm SV003' "+BLOCK+"; Sensui=bit brand (JP-style name) possible OEM; unverifiable while search down","retry_when_search_restored"),
(6140,"FAS-SHE-EYE-RING-4#","PCK","reject","R","no","no","pck_of_10_ok","no_asset",
 "tier2 start. q:'screw eye ring sheep eye No.4 10pcs Malaysia' "+BLOCK+"; commodity eye-screw pack generic_unbranded; prior reject upheld","shoot in-store"),
(4228,"HOS-CON-19-25MM-1'","PCS","reject","R","no","no","joint_19_25mm_ok","no_asset",
 "tier2 start. q:'power hose joint connector 19-25mm Malaysia' "+BLOCK+"; commodity hose joiner generic_unbranded; prior reject upheld","shoot in-store"),
(6252,"FIT-HDPE-NIP-1\"X1\"","PCS","reject","R","no","no","nipple_1in_ok","no_asset",
 "tier2 start. q:'HDPE nipple 1 inch Malaysia fitting' "+BLOCK+"; commodity fitting generic_unbranded; prior reject upheld","shoot in-store"),
(2803,"SWI-SOC-NNE-9498","PCS","pending","C","unknown","unknown","pcs_2gang_ok","unknown",
 "tier2 start. q:'NNE 9498 metal clad switched socket 2 gang 13A' "+BLOCK+"; NNE=metalclad switch brand; prior candidate unverifiable while search down","retry_when_search_restored"),
(3517,"ELE-T5-3'-CIELO-D/L","PCS","pending","C","unknown","unknown","fitting_3ft_ok","unknown",
 "tier2 start. q:'Cielo T5 LED batten 3FT 14W Malaysia' "+BLOCK+"; Cielo=T5 fitting brand (MY market) OEM site unknown; unverifiable while search down","retry_when_search_restored"),
(3228,"IND-CAS-FIX-1.5\"","PCS","pending","C","unknown","unknown","caster_1_5in_ok","unknown",
 "tier2 start. q:'TPE fixed caster DL5 1.5 inch Malaysia' "+BLOCK+"; sibling of 3347 same series; unverifiable while search down","retry_when_search_restored"),
(2794,"DOR-HAN-CF350-NA-L","PCS","pending","C","unknown","unknown","fitchet_left_ok","unknown",
 "tier2 start. q:'CF350 casement fitch fastener crescent handle left' "+BLOCK+"; CF350 model attribution unknown; unverifiable while search down","retry_when_search_restored"),
(4786,"CAP-01.8UF-400V","EA","pending","C","unknown","unknown","ea_ok","unknown",
 "tier2 start. q:'CPI capacitor Italy 400V 1.8uF' "+BLOCK+"; same CPI-marked cap family as 4890; unverifiable while search down","retry_when_search_restored"),
(2917,"DOR-STO-TRANSP-38MM","PCS","reject","R","no","no","stopper_25x38_ok","no_asset",
 "tier2 start. q:'transparent rubber door stopper 38mm Malaysia' "+BLOCK+"; commodity generic_unbranded; prior reject upheld","shoot in-store"),
(5275,"SWI-ADA-TRA-13A","PCS","pending","C","unknown","unknown","adaptor_es277ta2_ok","unknown",
 "tier2 start. q:'Eurosafe travel adaptor ES-277TA-2 13A Malaysia' "+BLOCK+"; Eurosafe=local brand attribution uncertain; unverifiable while search down","retry_when_search_restored"),
(4081,"CUT-DIS-MARK-12300-P036","PCS","pending","C","unknown","unknown","disc_4in_p36_ok","unknown",
 "tier2 start. q:'\"Mr Mark\" fibre disc P36 4 inch black' "+BLOCK+"; Mr.Mark=real tool-consumables brand; OEM page possible; unverifiable while search down","retry_when_search_restored"),
(4362,"CUT-DIS-W2451-100","PCS","pending","C","unknown","unknown","cutting_wheel_4in_ok","unknown",
 "tier2 start. q:'cutting wheel W2451 4 inch Malaysia' "+BLOCK+"; W2451 model attribution unknown; unverifiable while search down","retry_when_search_restored"),
(3062,"SWI-SOC-NNE-9499","PCS","pending","C","unknown","unknown","pcs_1gang_ok","unknown",
 "tier2 start. q:'NNE 9499 metal clad switched socket 1 gang 13A' "+BLOCK+"; NNE brand; prior candidate unverifiable while search down","retry_when_search_restored"),
(3210,"SWI-BUT-HOI-15A-250V","PCS","pending","C","unknown","unknown","hoist_button_ths21_ok","unknown",
 "tier2 start. q:'THS-21 hoist push button switch 15A 250V' "+BLOCK+"; THS-21 model attribution unknown; unverifiable while search down","retry_when_search_restored"),
(3495,"ELE-ADA-3WAY-MS-BS03L","PCS","pending","C","unknown","unknown","adaptor_bs03l_ok","unknown",
 "tier2 start. q:'Morries BS03L 3 way adaptor fused neon 13A' "+BLOCK+"; Morries MY brand; unverifiable while search down","retry_when_search_restored"),
(3932,"SWI-SOC-ELE-E011B","PCS","pending","C","unknown","unknown","switch_e011b_ok","unknown",
 "tier2 start. q:'Elegance E011B 16A 1 gang switch black Malaysia' "+BLOCK+"; Elegance=switch series brand attribution uncertain; unverifiable while search down","retry_when_search_restored"),
(3577,"VAL-ANG-CVL-CA9001","PCS","pending","C","unknown","unknown","angle_valve_ca9001_ok","unknown",
 "tier2 start. q:'Cavallo CA9001 stainless angle valve' "+BLOCK+" ; Cavallo=sanitary brand attribution uncertain; unverifiable while search down","retry_when_search_restored"),
(2769,"PAI-ROL-SET-CRI-424","SET","pending","C","unknown","unknown","roller_set_4in_x20_ok","unknown",
 "tier2 start. q:'Cristin tiger stripe paint roller set 4 inch' "+BLOCK+"; Cristin=Italian roller mfr (cristinpennelli?) possible; unverifiable while search down","retry_when_search_restored"),
(4154,"BAT-ENE-MIN-A23","PCK","pending","C","unknown","unknown","pck_8p1_ok","unknown",
 "tier2 start. q:'Energizer A23 battery 8P1 12V' "+BLOCK+"; Energizer OEM product; unverifiable while search down","retry_when_search_restored"),
(3410,"PLA-BAG-W500-0812","PACK","reject","R","no","no","pack_white_500g_ok","no_asset",
 "tier2 start. q:'plastic bag 8 x 12 white 500g Malaysia' "+BLOCK+"; packaging commodity generic_unbranded; prior reject upheld","shoot in-store"),
(3516,"ELE-CAB-PVC-4.00MM-GRE-MTR","MTR","pending","C","unknown","unknown","mtr_cut_from_100m_ok","unknown",
 "tier2 start. q:'KTK PVC insulated cable 4mm green single core Malaysia' "+BLOCK+"; KTK=cable brand attribution uncertain; unverifiable while search down","retry_when_search_restored"),
(3789,"PEN-TES-BLM452","PCS","pending","C","unknown","unknown","pen_blm452_ok","unknown",
 "tier2 start. q:'Blimax test pen BLM452' "+BLOCK+"; Blimax=tool brand attribution uncertain; unverifiable while search down","retry_when_search_restored"),
(4304,"CUT-GRI-MJ021-100","PCS","pending","C","unknown","unknown","grinding_wheel_4in_ok","unknown",
 "tier2 start. q:'QS grinding wheel MJ-021 4 inch' "+BLOCK+"; MJ-021/QS attribution unknown; unverifiable while search down","retry_when_search_restored"),
(3234,"SWI-PLK-NEO-1380N","PCS","pending","C","unknown","unknown","switch_1380n_ok","unknown",
 "tier2 start. q:'PLK neon heater switch 20A 1380N Malaysia' "+BLOCK+"; PLK brand attribution uncertain; unverifiable while search down","retry_when_search_restored"),
(3314,"ELE-D/L-MGM-MQTL2048-3000K","PCS","pending","C","unknown","unknown","eyeball_mqtl2048_ok","unknown",
 "tier2 start. q:'MGM MQTL2048 eyeball downlight 7W' "+BLOCK+"; MGM=lighting brand attribution uncertain; unverifiable while search down","retry_when_search_restored"),
(2974,"LOC-CZS-L50MM","PCS","pending","C","unknown","unknown","padlock_l50_ok","unknown",
 "tier2 start. q:'CZS 360 padlock 50mm' "+BLOCK+"; CZS brand attribution uncertain; unverifiable while search down","retry_when_search_restored"),
(4604,"BRA-L-SSS-90X90MM","PCS","reject","R","no","no","bracket_90x90_ok","no_asset",
 "tier2 start. q:'stainless steel L bracket 90x90mm Malaysia' "+BLOCK+"; commodity bracket generic_unbranded; prior reject upheld","shoot in-store"),
(4176,"SHH-LINE-WHI-NO.15","PCS","reject","R","no","no","line_no15_ok","no_asset",
 "tier2 start. q:'nylon monofilament fishing line white No.15 Malaysia' "+BLOCK+"; bulk line commodity generic_unbranded; prior reject upheld","shoot in-store"),
(3732,"FAS-SCR-P/H-1 1/4\" X 8#","PCK","reject","R","no","no","pck_of_20_ok","no_asset",
 "tier2 start. q:'SR pan head self drilling screw 8 x 1-1/4 20pcs' "+BLOCK+"; SR repack commodity generic_unbranded; prior reject upheld","shoot in-store"),
(4159,"CUT-ELE-EMC420","PCS","pending","C","unknown","unknown","disc_emc420_ok","unknown",
 "tier2 start. q:'\"Gold Elephant\" EMC420 cutting disc 4 x 2.0' "+BLOCK+"; Gold Elephant abrasive brand; unverifiable while search down","retry_when_search_restored"),
(7100,"FAS-SCR-DRY-BLA-6#3/4\"","PCK","reject","R","no","no","pck_of_20_ok","no_asset",
 "tier2 start. q:'Hunter black drywall screw 6 x 3/4 20pcs Malaysia' "+BLOCK+"; Hunter/bk local repack house brand; commodity; prior reject upheld","shoot in-store"),
(4655,"ELE-LRD-MOT-3357","BOX","pending","C","unknown","unknown","overload_37_50a_ok","unknown",
 "tier2 start. q:'thermal overload relay 3357 37-50A motor starter' "+BLOCK+"; 3357 relay model attribution unknown (maybe Delab/Generic); unverifiable while search down","retry_when_search_restored"),
(2930,"ELE-D/L-PHL-59466-RD-4000K","SET","pending","C","unknown","unknown","set_ok","unknown",
 "tier2 start. q:'Philips Meson 59466 round 4000K LED downlight' "+BLOCK+"; Philips OEM line; need true PURL; unverifiable while search down","retry_when_search_restored"),
(3705,"FAS-BOL-EXP-TRAC140-M10X110X60","PCS","reject","R","no","no","bolt_m10x110_ok","no_asset",
 "tier2 start. q:'brain hook expansion bolt TRAC140 M10x110 Malaysia' "+BLOCK+"; Brain/TRAC=local fastener repack naming, commodity wedge anchor generic_unbranded; prior reject upheld","shoot in-store"),
(2875,"PAI-ROL-SET-CRI-416","SET","pending","C","unknown","unknown","roller_set_4in_x15_ok","unknown",
 "tier2 start. q:'Cristin tiger stripe roller set 4 x 15' "+BLOCK+"; sibling of 2769; unverifiable while search down","retry_when_search_restored"),
(4858,"BRA-S/S-L-50383","PCS","reject","R","no","no","bracket_50x50_ok","no_asset",
 "tier2 start. q:'stainless steel L bracket 50x50mm Malaysia' "+BLOCK+"; commodity bracket generic_unbranded, 50383=sku suffix; prior reject upheld","shoot in-store"),
]

def main():
    with open(OUT, "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh, quoting=csv.QUOTE_MINIMAL)
        w.writerow(HDR)
        for r in ROWS:
            pos, code, uom, dec, conf, fin, mod, uoma, rights, reason, human = r
            w.writerow([pos, code, uom, "", "", dec, conf, fin, mod, uoma, rights,
                        reason, human])
    print("wrote", len(ROWS), "rows")

if __name__ == "__main__":
    main()
